name: Replay Pointer Update

permissions:
  contents: write

on:
  repository_dispatch:
    types: [replay-pointer-updated]
  workflow_dispatch:
    inputs:
      md_tag:
        description: 'MD Tag (z.B. MD08)'
        required: true
        type: string

jobs:
  update-replay-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Data Repo
        uses: actions/checkout@v4
        with:
          repository: Grizz4h/highspeed-pux-data
          token: ${{ secrets.PUBLISH_TOKEN }}

      - name: Extract MD Tag from Workflow Input or Commit Message
        id: md
        shell: bash
        run: |
          if [ -n "${{ inputs.md_tag }}" ]; then
            MD_TAG="${{ inputs.md_tag }}"
          else
            # Fallback: Versuche MD aus aktuellem Commit zu extrahieren
            MD_TAG=$(git log -1 --pretty=%s | grep -oP 'MD\d+' || echo "MD01")
          fi
          echo "md_tag=$MD_TAG" >> $GITHUB_OUTPUT
          echo "MD Tag: $MD_TAG"

      - name: Find Latest Season and Spieltag
        id: season
        shell: bash
        run: |
          SEASON=$(ls -d replays/saison_* 2>/dev/null | sort -V | tail -1 | grep -oP 'saison_\K\d+' || echo "01")
          
          # Extract matchday from MD tag if provided, else try to read from replay_matchday.json
          RAW_MD=$(echo "${{ steps.md.outputs.md_tag }}" | grep -oP 'MD\K\d+' || true)
          if [ -n "$RAW_MD" ]; then
            SPIELTAG=$(printf "%02d" "$RAW_MD")
          else
            # Try to detect latest replay_matchday.json and read its matchday
            LATEST_MD_JSON=$(ls replays/saison_${SEASON}/spieltag_*/replay_matchday.json 2>/dev/null | sort -V | tail -1 || true)
            if [ -n "$LATEST_MD_JSON" ]; then
              SPIELTAG=$(jq -r '.matchday' "$LATEST_MD_JSON" 2>/dev/null | awk '{printf "%02d", $0}' )
            else
              SPIELTAG="01"
            fi
          fi
          
          echo "season=$SEASON" >> $GITHUB_OUTPUT
          echo "spieltag=$SPIELTAG" >> $GITHUB_OUTPUT
          echo "Saison: $SEASON, Spieltag: $SPIELTAG"

      - name: Verify Replay Data Exists
        shell: bash
        run: |
          REPLAY_SOURCE="replays/saison_${{ steps.season.outputs.season }}/spieltag_${{ steps.season.outputs.spieltag }}"
          
          if [ ! -d "$REPLAY_SOURCE" ]; then
            echo "❌ Replay-Quelle nicht gefunden: $REPLAY_SOURCE"
            ls -la replays/saison_${{ steps.season.outputs.season }}/ || echo "Season dir nicht gefunden"
            exit 1
          fi
          
          echo "✅ Replay-Quelle gefunden: $REPLAY_SOURCE"
          ls -la "$REPLAY_SOURCE"

      - name: Checkout Website Repo
        uses: actions/checkout@v4
        with:
          repository: Grizz4h/highspeed-web
          token: ${{ secrets.PUBLISH_TOKEN }}
          path: web
          ref: main

      - name: Copy Replay Data to Web Repo
        shell: bash
        run: |
          REPLAY_SOURCE="replays/saison_${{ steps.season.outputs.season }}/spieltag_${{ steps.season.outputs.spieltag }}"
          WEB_TARGET="web/public/data/replays"
          
          mkdir -p "$WEB_TARGET"
          rsync -av --delete "$REPLAY_SOURCE/" "$WEB_TARGET/"
          echo "✅ Replay-Daten kopiert"

      - name: Commit and Push to Web Repo
        shell: bash
        run: |
          cd web
          git config user.name "SSOT Publisher"
          git config user.email "actions@github.com"
          git add public/data/replays/
          
          if git diff --staged --quiet; then
            echo "ℹ️ Keine Änderungen - nichts zu committen"
          else
            git commit -m "chore(replay): update to ${{ steps.md.outputs.md_tag }}"
            git push origin main
            echo "✅ Replay-Daten zu web/main gepusht"
          fi
