# Diese Datei wurde automatisch aus players_rated.json erzeugt.
# Web-Format: reduzierte Kader für die Webseite.

nord_teams = [{'Team': 'Bad Nauheim Devils',
  'Momentum': 0,
  'Players': [{'Name': 'Justinu MacPherar', 'Offense': 82, 'Defense': 72, 'Speed': 80, 'Chemistry': 72},
              {'Name': 'Jorde Hickmotik', 'Offense': 86, 'Defense': 74, 'Speed': 75, 'Chemistry': 73},
              {'Name': 'Juliano Lautenschlagov', 'Offense': 80, 'Defense': 71, 'Speed': 75, 'Chemistry': 73},
              {'Name': 'Parkera Bowlestto', 'Offense': 72, 'Defense': 63, 'Speed': 74, 'Chemistry': 67},
              {'Name': 'Zachi Kaisdunov', 'Offense': 73, 'Defense': 65, 'Speed': 73, 'Chemistry': 67},
              {'Name': 'Andre Biresven', 'Offense': 73, 'Defense': 63, 'Speed': 73, 'Chemistry': 68},
              {'Name': 'Davisa Kochik', 'Offense': 68, 'Defense': 56, 'Speed': 72, 'Chemistry': 65},
              {'Name': 'Raphaelo Jakovlov', 'Offense': 71, 'Defense': 69, 'Speed': 71, 'Chemistry': 70},
              {'Name': 'Taylori Vausan', 'Offense': 71, 'Defense': 72, 'Speed': 69, 'Chemistry': 68},
              {'Name': 'Lukasu Ribarov', 'Offense': 68, 'Defense': 71, 'Speed': 70, 'Chemistry': 72},
              {'Name': 'Justinu Volekinov', 'Offense': 68, 'Defense': 73, 'Speed': 67, 'Chemistry': 72},
              {'Name': 'Marcu ElSaysen', 'Offense': 64, 'Defense': 78, 'Speed': 68, 'Chemistry': 74},
              {'Name': 'Sebu Bengtsvik', 'Offense': 64, 'Defense': 76, 'Speed': 66, 'Chemistry': 68},
              {'Name': 'Garreta Prudenvik', 'Offense': 63, 'Defense': 68, 'Speed': 68, 'Chemistry': 71},
              {'Name': 'Mariusi Erken', 'Offense': 63, 'Defense': 66, 'Speed': 68, 'Chemistry': 69},
              {'Name': 'Phe Kuhneksen', 'Offense': 64, 'Defense': 65, 'Speed': 63, 'Chemistry': 62},
              {'Name': 'Simona Gnypov', 'Offense': 64, 'Defense': 72, 'Speed': 65, 'Chemistry': 71},
              {'Name': 'Christophera Fischven', 'Offense': 64, 'Defense': 67, 'Speed': 63, 'Chemistry': 64},
              {'Name': 'Lui Niehustto', 'Offense': 67, 'Defense': 61, 'Speed': 61, 'Chemistry': 57},
              {'Name': 'Kevine Handschdunov', 'Offense': 63, 'Defense': 73, 'Speed': 66, 'Chemistry': 73},
              {'Name': 'Sebu Cimmermven', 'Offense': 63, 'Defense': 66, 'Speed': 63, 'Chemistry': 61},
              {'Name': 'Kevine Bickar', 'Offense': 60, 'Defense': 73, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Tjarka Kölschov', 'Offense': 59, 'Defense': 72, 'Speed': 55, 'Chemistry': 64},
              {'Name': 'Fabianu Nifosan', 'Offense': 59, 'Defense': 74, 'Speed': 56, 'Chemistry': 66},
              {'Name': 'Xavera Tippsen', 'Offense': 59, 'Defense': 69, 'Speed': 58, 'Chemistry': 65},
              {'Name': 'Phe Bidoulov', 'Offense': 59, 'Defense': 76, 'Speed': 61, 'Chemistry': 72},
              {'Name': 'Rike Gaidven', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Fabio Kosvik', 'Offense': 59, 'Defense': 72, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Time Kosvik', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Pata Seifervik', 'Offense': 59, 'Defense': 72, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Geraldo Kuhnnik', 'Offense': 95, 'Defense': 91, 'Speed': 96, 'Chemistry': 88},
              {'Name': 'Finni Becklek', 'Offense': 47, 'Defense': 74, 'Speed': 69, 'Chemistry': 46}]},
 {'Team': 'Bremerhaven Trident',
  'Momentum': 0,
  'Players': [{'Name': 'Bennu Rossmyinov', 'Offense': 85, 'Defense': 66, 'Speed': 80, 'Chemistry': 77},
              {'Name': 'Ale Frieov', 'Offense': 80, 'Defense': 76, 'Speed': 79, 'Chemistry': 78},
              {'Name': 'Andyo Miellek', 'Offense': 78, 'Defense': 65, 'Speed': 78, 'Chemistry': 74},
              {'Name': 'Zigi Jeglicen', 'Offense': 78, 'Defense': 70, 'Speed': 79, 'Chemistry': 74},
              {'Name': 'Christiana Wejsen', 'Offense': 83, 'Defense': 55, 'Speed': 78, 'Chemistry': 66},
              {'Name': 'Miha Verlicinov', 'Offense': 77, 'Defense': 72, 'Speed': 77, 'Chemistry': 75},
              {'Name': 'Nicolasa Krämmov', 'Offense': 77, 'Defense': 83, 'Speed': 77, 'Chemistry': 83},
              {'Name': 'Akite Hirosdunov', 'Offense': 75, 'Defense': 70, 'Speed': 77, 'Chemistry': 71},
              {'Name': 'Jano Urbasik', 'Offense': 79, 'Defense': 74, 'Speed': 76, 'Chemistry': 71},
              {'Name': 'Mati Abttli', 'Offense': 74, 'Defense': 75, 'Speed': 76, 'Chemistry': 77},
              {'Name': 'Ludwu Byströov', 'Offense': 72, 'Defense': 87, 'Speed': 75, 'Chemistry': 83},
              {'Name': 'Maxe Görtzik', 'Offense': 71, 'Defense': 80, 'Speed': 75, 'Chemistry': 81},
              {'Name': 'Rossa Mauerven', 'Offense': 75, 'Defense': 70, 'Speed': 73, 'Chemistry': 76},
              {'Name': 'Nicholasu Jenvik', 'Offense': 66, 'Defense': 66, 'Speed': 72, 'Chemistry': 70},
              {'Name': 'Coltu Conradtli', 'Offense': 70, 'Defense': 73, 'Speed': 73, 'Chemistry': 68},
              {'Name': 'Phe Bruggissik', 'Offense': 71, 'Defense': 61, 'Speed': 71, 'Chemistry': 62},
              {'Name': 'Vlo Emingik', 'Offense': 69, 'Defense': 74, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Nine Kindik', 'Offense': 65, 'Defense': 72, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Justinu Büsingsen', 'Offense': 65, 'Defense': 72, 'Speed': 67, 'Chemistry': 70},
              {'Name': 'Rayanu Bettahsen', 'Offense': 63, 'Defense': 80, 'Speed': 61, 'Chemistry': 71},
              {'Name': 'Fabianu Herrinov', 'Offense': 63, 'Defense': 65, 'Speed': 65, 'Chemistry': 67},
              {'Name': 'Maxima Rauschov', 'Offense': 60, 'Defense': 74, 'Speed': 68, 'Chemistry': 77},
              {'Name': 'Kristersi Gudlevskar', 'Offense': 66, 'Defense': 87, 'Speed': 80, 'Chemistry': 62},
              {'Name': 'Jule Hudacinov', 'Offense': 84, 'Defense': 85, 'Speed': 89, 'Chemistry': 73},
              {'Name': 'Leona Hungereckdunov', 'Offense': 73, 'Defense': 85, 'Speed': 82, 'Chemistry': 69}]},
 {'Team': 'Düsseldorf Aurora',
  'Momentum': 0,
  'Players': [{'Name': 'Eriki Bradforovik', 'Offense': 93, 'Defense': 73, 'Speed': 84, 'Chemistry': 75},
              {'Name': 'Yushirohe Hiranik', 'Offense': 91, 'Defense': 70, 'Speed': 82, 'Chemistry': 72},
              {'Name': 'Turo Lindenvik', 'Offense': 86, 'Defense': 72, 'Speed': 81, 'Chemistry': 72},
              {'Name': 'Maximiliana Fabar', 'Offense': 76, 'Defense': 62, 'Speed': 78, 'Chemistry': 66},
              {'Name': 'Michaelo Clarkov', 'Offense': 69, 'Defense': 68, 'Speed': 73, 'Chemistry': 70},
              {'Name': 'Kevine Orendorsen', 'Offense': 72, 'Defense': 75, 'Speed': 72, 'Chemistry': 75},
              {'Name': 'Lucase Lessiin', 'Offense': 73, 'Defense': 55, 'Speed': 70, 'Chemistry': 61},
              {'Name': 'Leona Niederen', 'Offense': 72, 'Defense': 71, 'Speed': 71, 'Chemistry': 68},
              {'Name': 'Maxe Balinov', 'Offense': 72, 'Defense': 79, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Simona Thien', 'Offense': 68, 'Defense': 73, 'Speed': 70, 'Chemistry': 73},
              {'Name': 'Kevine Magintli', 'Offense': 65, 'Defense': 69, 'Speed': 70, 'Chemistry': 71},
              {'Name': 'Emilo Quaasov', 'Offense': 65, 'Defense': 72, 'Speed': 69, 'Chemistry': 73},
              {'Name': 'Lennya Boosin', 'Offense': 65, 'Defense': 74, 'Speed': 69, 'Chemistry': 73},
              {'Name': 'Moritzi Kukukin', 'Offense': 63, 'Defense': 73, 'Speed': 68, 'Chemistry': 74},
              {'Name': 'Kevine Norénnik', 'Offense': 65, 'Defense': 69, 'Speed': 66, 'Chemistry': 71},
              {'Name': 'Luce Tostar', 'Offense': 71, 'Defense': 76, 'Speed': 79, 'Chemistry': 64},
              {'Name': 'Eriki Browntto', 'Offense': 64, 'Defense': 60, 'Speed': 65, 'Chemistry': 60},
              {'Name': 'Nicolasa Geitnar', 'Offense': 62, 'Defense': 71, 'Speed': 66, 'Chemistry': 72},
              {'Name': 'Kristianu Blumenschro', 'Offense': 68, 'Defense': 68, 'Speed': 63, 'Chemistry': 61},
              {'Name': 'Kevine Niedenar', 'Offense': 60, 'Defense': 74, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Sinani Akdaglek', 'Offense': 59, 'Defense': 64, 'Speed': 55, 'Chemistry': 59},
              {'Name': 'Reede Starkar', 'Offense': 60, 'Defense': 74, 'Speed': 57, 'Chemistry': 66},
              {'Name': 'Marca Münzenik', 'Offense': 60, 'Defense': 69, 'Speed': 58, 'Chemistry': 65},
              {'Name': 'Daniele Assavolyov', 'Offense': 60, 'Defense': 73, 'Speed': 61, 'Chemistry': 69},
              {'Name': 'Joele Hofik', 'Offense': 60, 'Defense': 73, 'Speed': 64, 'Chemistry': 72},
              {'Name': 'Ryani Olvik', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Nikla Lunear', 'Offense': 73, 'Defense': 85, 'Speed': 83, 'Chemistry': 67},
              {'Name': 'Ryani Bednarov', 'Offense': 67, 'Defense': 86, 'Speed': 81, 'Chemistry': 64},
              {'Name': 'Leona Hümar', 'Offense': 42, 'Defense': 81, 'Speed': 67, 'Chemistry': 42},
              {'Name': 'Seano Kuklokro', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40}]},
 {'Team': 'Frankfurt Core',
  'Momentum': 0,
  'Players': [{'Name': 'Linusa Frötli', 'Offense': 77, 'Defense': 63, 'Speed': 79, 'Chemistry': 68},
              {'Name': 'Camerone Bracar', 'Offense': 84, 'Defense': 68, 'Speed': 79, 'Chemistry': 72},
              {'Name': 'Makso Matushkov', 'Offense': 78, 'Defense': 53, 'Speed': 76, 'Chemistry': 60},
              {'Name': 'Tyi Glovtto', 'Offense': 74, 'Defense': 60, 'Speed': 75, 'Chemistry': 65},
              {'Name': 'Mati Wedmanovik', 'Offense': 72, 'Defense': 43, 'Speed': 74, 'Chemistry': 58},
              {'Name': 'Michaelo Joyauxtto', 'Offense': 70, 'Defense': 53, 'Speed': 73, 'Chemistry': 64},
              {'Name': 'Dennise Lobachro', 'Offense': 74, 'Defense': 49, 'Speed': 72, 'Chemistry': 63},
              {'Name': 'Christophera Wilkiinov', 'Offense': 71, 'Defense': 41, 'Speed': 71, 'Chemistry': 55},
              {'Name': 'Daniele Pfaffengen', 'Offense': 69, 'Defense': 61, 'Speed': 72, 'Chemistry': 66},
              {'Name': 'Ryani McKierntto', 'Offense': 66, 'Defense': 55, 'Speed': 72, 'Chemistry': 65},
              {'Name': 'Time Kosvik', 'Offense': 68, 'Defense': 64, 'Speed': 68, 'Chemistry': 67},
              {'Name': 'Jakobu Liljlek', 'Offense': 66, 'Defense': 71, 'Speed': 66, 'Chemistry': 65},
              {'Name': 'Nathi Burnsvik', 'Offense': 65, 'Defense': 70, 'Speed': 66, 'Chemistry': 67},
              {'Name': 'Fabio Kosvik', 'Offense': 64, 'Defense': 71, 'Speed': 69, 'Chemistry': 74},
              {'Name': 'Tommye Pasanen', 'Offense': 62, 'Defense': 63, 'Speed': 68, 'Chemistry': 69},
              {'Name': 'Markusu Schweigdunov', 'Offense': 63, 'Defense': 63, 'Speed': 69, 'Chemistry': 66},
              {'Name': 'Noahi Dunhamro', 'Offense': 63, 'Defense': 65, 'Speed': 69, 'Chemistry': 69},
              {'Name': 'Cartere Proftin', 'Offense': 63, 'Defense': 68, 'Speed': 63, 'Chemistry': 65},
              {'Name': 'Cartere Rowneyovik', 'Offense': 62, 'Defense': 74, 'Speed': 66, 'Chemistry': 73},
              {'Name': 'Reida McNeilov', 'Offense': 61, 'Defense': 53, 'Speed': 67, 'Chemistry': 62},
              {'Name': 'Daniele Wirtvik', 'Offense': 63, 'Defense': 64, 'Speed': 62, 'Chemistry': 64},
              {'Name': 'Kevine Bickar', 'Offense': 61, 'Defense': 72, 'Speed': 62, 'Chemistry': 68},
              {'Name': 'Sebu Cimmermven', 'Offense': 60, 'Defense': 74, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Phe Bidoulov', 'Offense': 59, 'Defense': 72, 'Speed': 56, 'Chemistry': 65},
              {'Name': 'Codye Brennov', 'Offense': 73, 'Defense': 84, 'Speed': 85, 'Chemistry': 65},
              {'Name': 'Mirke Pantkowsov', 'Offense': 82, 'Defense': 83, 'Speed': 88, 'Chemistry': 73},
              {'Name': 'Rodione Schumachdunov', 'Offense': 41, 'Defense': 70, 'Speed': 61, 'Chemistry': 42}]},
 {'Team': 'Iserlohn Miners',
  'Momentum': 0,
  'Players': [{'Name': 'Daniele Fischbsen', 'Offense': 92, 'Defense': 68, 'Speed': 84, 'Chemistry': 72},
              {'Name': 'Colino Ugbekilov', 'Offense': 77, 'Defense': 71, 'Speed': 81, 'Chemistry': 74},
              {'Name': 'Ericu Cornvik', 'Offense': 81, 'Defense': 71, 'Speed': 79, 'Chemistry': 74},
              {'Name': 'Juliano Napravndunov', 'Offense': 83, 'Defense': 66, 'Speed': 78, 'Chemistry': 69},
              {'Name': 'Christiana Thomastto', 'Offense': 81, 'Defense': 61, 'Speed': 78, 'Chemistry': 66},
              {'Name': 'Kyli Woodik', 'Offense': 68, 'Defense': 68, 'Speed': 72, 'Chemistry': 71},
              {'Name': 'Tylera Bolandlek', 'Offense': 71, 'Defense': 66, 'Speed': 72, 'Chemistry': 69},
              {'Name': 'Henrike Törnqvven', 'Offense': 68, 'Defense': 66, 'Speed': 69, 'Chemistry': 70},
              {'Name': 'Taro Jentzscven', 'Offense': 65, 'Defense': 73, 'Speed': 66, 'Chemistry': 71},
              {'Name': 'Eiriki Salsten', 'Offense': 64, 'Defense': 60, 'Speed': 70, 'Chemistry': 65},
              {'Name': 'Matiasu Lasen', 'Offense': 63, 'Defense': 65, 'Speed': 67, 'Chemistry': 67},
              {'Name': 'Coltona Jobksen', 'Offense': 62, 'Defense': 70, 'Speed': 64, 'Chemistry': 68},
              {'Name': 'Johe Husstli', 'Offense': 61, 'Defense': 57, 'Speed': 67, 'Chemistry': 65},
              {'Name': 'Robino Norelltto', 'Offense': 61, 'Defense': 49, 'Speed': 69, 'Chemistry': 62},
              {'Name': 'Anthonyu Camarven', 'Offense': 63, 'Defense': 72, 'Speed': 63, 'Chemistry': 62},
              {'Name': 'Macoyi Erkampin', 'Offense': 60, 'Defense': 63, 'Speed': 68, 'Chemistry': 70},
              {'Name': 'Lenu Nielectli', 'Offense': 60, 'Defense': 73, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Bencu Farkastto', 'Offense': 60, 'Defense': 73, 'Speed': 57, 'Chemistry': 65},
              {'Name': 'Goro Radionik', 'Offense': 59, 'Defense': 70, 'Speed': 58, 'Chemistry': 65},
              {'Name': 'Nilso Eltenovik', 'Offense': 59, 'Defense': 72, 'Speed': 59, 'Chemistry': 68},
              {'Name': 'Mano Alinov', 'Offense': 60, 'Defense': 71, 'Speed': 60, 'Chemistry': 68},
              {'Name': 'Noela Saffrro', 'Offense': 60, 'Defense': 71, 'Speed': 61, 'Chemistry': 68},
              {'Name': 'Jakuba Borzeckro', 'Offense': 60, 'Defense': 68, 'Speed': 63, 'Chemistry': 67},
              {'Name': 'Lui Niehustto', 'Offense': 59, 'Defense': 64, 'Speed': 64, 'Chemistry': 68},
              {'Name': 'Daniele Geigtto', 'Offense': 60, 'Defense': 68, 'Speed': 64, 'Chemistry': 69},
              {'Name': 'Daniele Neuven', 'Offense': 60, 'Defense': 66, 'Speed': 67, 'Chemistry': 69},
              {'Name': 'Hendrike Hantto', 'Offense': 70, 'Defense': 87, 'Speed': 82, 'Chemistry': 61},
              {'Name': 'Andi Jenikdunov', 'Offense': 81, 'Defense': 86, 'Speed': 87, 'Chemistry': 72}]},
 {'Team': 'Köln Blitzhaie',
  'Momentum': 0,
  'Players': [{'Name': 'Grege MacLeinov', 'Offense': 99, 'Defense': 85, 'Speed': 91, 'Chemistry': 84},
              {'Name': 'Pata Russelnik', 'Offense': 99, 'Defense': 80, 'Speed': 90, 'Chemistry': 83},
              {'Name': 'Natu Schnarven', 'Offense': 86, 'Defense': 61, 'Speed': 83, 'Chemistry': 66},
              {'Name': 'Valttera Kemiläinlek', 'Offense': 82, 'Defense': 80, 'Speed': 79, 'Chemistry': 79},
              {'Name': 'LouisMarca Aubryik', 'Offense': 76, 'Defense': 66, 'Speed': 78, 'Chemistry': 71},
              {'Name': 'Oliwo Kasktli', 'Offense': 75, 'Defense': 64, 'Speed': 77, 'Chemistry': 71},
              {'Name': 'Dominiki Bokksen', 'Offense': 73, 'Defense': 70, 'Speed': 77, 'Chemistry': 73},
              {'Name': 'Tanno Kerven', 'Offense': 70, 'Defense': 72, 'Speed': 76, 'Chemistry': 73},
              {'Name': 'Ryani MacInndunov', 'Offense': 74, 'Defense': 69, 'Speed': 74, 'Chemistry': 73},
              {'Name': 'VeliMatta Vittasmäovik', 'Offense': 69, 'Defense': 86, 'Speed': 73, 'Chemistry': 82},
              {'Name': 'Maximiliana Kammerven', 'Offense': 69, 'Defense': 72, 'Speed': 73, 'Chemistry': 75},
              {'Name': 'Parkera Tuomiov', 'Offense': 72, 'Defense': 69, 'Speed': 71, 'Chemistry': 66},
              {'Name': 'Juhanu Tyrväinsen', 'Offense': 70, 'Defense': 66, 'Speed': 71, 'Chemistry': 71},
              {'Name': 'Bradya Austinov', 'Offense': 66, 'Defense': 66, 'Speed': 70, 'Chemistry': 72},
              {'Name': 'Fri Storminov', 'Offense': 66, 'Defense': 68, 'Speed': 67, 'Chemistry': 68},
              {'Name': 'Moritzi Müllar', 'Offense': 64, 'Defense': 60, 'Speed': 70, 'Chemistry': 68},
              {'Name': 'Dominiki Uhen', 'Offense': 64, 'Defense': 75, 'Speed': 65, 'Chemistry': 72},
              {'Name': 'Maximiliana Glötzlsen', 'Offense': 61, 'Defense': 68, 'Speed': 67, 'Chemistry': 72},
              {'Name': 'Robino Calstar', 'Offense': 61, 'Defense': 76, 'Speed': 62, 'Chemistry': 71},
              {'Name': 'Kevine Niedenar', 'Offense': 61, 'Defense': 70, 'Speed': 63, 'Chemistry': 68},
              {'Name': 'Maxe Ziergiebar', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Luce Münzenik', 'Offense': 59, 'Defense': 72, 'Speed': 55, 'Chemistry': 64},
              {'Name': 'Marca Münzenik', 'Offense': 60, 'Defense': 71, 'Speed': 60, 'Chemistry': 66},
              {'Name': 'Steni Fischven', 'Offense': 59, 'Defense': 70, 'Speed': 63, 'Chemistry': 70},
              {'Name': 'Jannu Juvonven', 'Offense': 58, 'Defense': 90, 'Speed': 77, 'Chemistry': 60},
              {'Name': 'Felixe Brücklek', 'Offense': 65, 'Defense': 87, 'Speed': 79, 'Chemistry': 64},
              {'Name': 'Toba Ancickvik', 'Offense': 65, 'Defense': 80, 'Speed': 78, 'Chemistry': 62},
              {'Name': 'Aaronu Kaisdunov', 'Offense': 42, 'Defense': 65, 'Speed': 63, 'Chemistry': 42}]},
 {'Team': 'Krefeld Kernschlag',
  'Momentum': 0,
  'Players': [{'Name': 'Davisa Vandanven', 'Offense': 86, 'Defense': 81, 'Speed': 83, 'Chemistry': 77},
              {'Name': 'Jonathane Matsumik', 'Offense': 81, 'Defense': 77, 'Speed': 83, 'Chemistry': 77},
              {'Name': 'Marcu Müllar', 'Offense': 81, 'Defense': 66, 'Speed': 81, 'Chemistry': 70},
              {'Name': 'Maxe Newtonik', 'Offense': 83, 'Defense': 70, 'Speed': 81, 'Chemistry': 71},
              {'Name': 'Daniele Bruchtto', 'Offense': 81, 'Defense': 65, 'Speed': 79, 'Chemistry': 72},
              {'Name': 'Marki Zengerlov', 'Offense': 75, 'Defense': 76, 'Speed': 78, 'Chemistry': 76},
              {'Name': 'Mathe Santoslek', 'Offense': 86, 'Defense': 60, 'Speed': 78, 'Chemistry': 66},
              {'Name': 'Philu Gogullik', 'Offense': 76, 'Defense': 70, 'Speed': 77, 'Chemistry': 72},
              {'Name': 'Adamo Payerlven', 'Offense': 86, 'Defense': 66, 'Speed': 75, 'Chemistry': 69},
              {'Name': 'Ale Weissin', 'Offense': 81, 'Defense': 78, 'Speed': 76, 'Chemistry': 77},
              {'Name': 'Zacka Dybowskovik', 'Offense': 69, 'Defense': 81, 'Speed': 72, 'Chemistry': 77},
              {'Name': 'Tima Schützan', 'Offense': 69, 'Defense': 71, 'Speed': 69, 'Chemistry': 70},
              {'Name': 'Stevene Raabik', 'Offense': 65, 'Defense': 77, 'Speed': 70, 'Chemistry': 75},
              {'Name': 'Davida Cernyinov', 'Offense': 69, 'Defense': 68, 'Speed': 66, 'Chemistry': 65},
              {'Name': 'Maximiliana Hopsen', 'Offense': 63, 'Defense': 75, 'Speed': 66, 'Chemistry': 71},
              {'Name': 'Micka Köhltli', 'Offense': 63, 'Defense': 79, 'Speed': 67, 'Chemistry': 77},
              {'Name': 'Roopu Mäkitalik', 'Offense': 62, 'Defense': 70, 'Speed': 63, 'Chemistry': 65},
              {'Name': 'Carlo Konztli', 'Offense': 62, 'Defense': 74, 'Speed': 64, 'Chemistry': 73},
              {'Name': 'Nicli Focksvik', 'Offense': 62, 'Defense': 71, 'Speed': 60, 'Chemistry': 64},
              {'Name': 'Leonharda Koruslek', 'Offense': 59, 'Defense': 66, 'Speed': 56, 'Chemistry': 61},
              {'Name': 'Oliveri Mebusov', 'Offense': 59, 'Defense': 69, 'Speed': 58, 'Chemistry': 65},
              {'Name': 'Eriki Buschik', 'Offense': 59, 'Defense': 75, 'Speed': 61, 'Chemistry': 71},
              {'Name': 'Jano Nijenhven', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Felixe Bickar', 'Offense': 82, 'Defense': 87, 'Speed': 86, 'Chemistry': 80},
              {'Name': 'Jule Schultov', 'Offense': 48, 'Defense': 88, 'Speed': 72, 'Chemistry': 48},
              {'Name': 'Ola Blumenkan', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40}]},
 {'Team': 'Kassel Zenit',
  'Momentum': 0,
  'Players': [{'Name': 'Tristano Keckvik', 'Offense': 89, 'Defense': 71, 'Speed': 81, 'Chemistry': 72},
              {'Name': 'Tylera Benik', 'Offense': 85, 'Defense': 74, 'Speed': 82, 'Chemistry': 73},
              {'Name': 'Hunti Garlenar', 'Offense': 84, 'Defense': 71, 'Speed': 81, 'Chemistry': 72},
              {'Name': 'Dominicu Turgetto', 'Offense': 85, 'Defense': 73, 'Speed': 79, 'Chemistry': 74},
              {'Name': 'Boda Wildven', 'Offense': 74, 'Defense': 80, 'Speed': 76, 'Chemistry': 77},
              {'Name': 'Yanno Valentin', 'Offense': 78, 'Defense': 70, 'Speed': 75, 'Chemistry': 72},
              {'Name': 'Darra Mieszkowsovik', 'Offense': 72, 'Defense': 80, 'Speed': 74, 'Chemistry': 79},
              {'Name': 'Mita Hoelschinov', 'Offense': 72, 'Defense': 70, 'Speed': 74, 'Chemistry': 74},
              {'Name': 'Jake Weidnar', 'Offense': 72, 'Defense': 75, 'Speed': 72, 'Chemistry': 76},
              {'Name': 'Andrewe Bodnarchro', 'Offense': 71, 'Defense': 71, 'Speed': 72, 'Chemistry': 71},
              {'Name': 'Laurine Braunovik', 'Offense': 70, 'Defense': 70, 'Speed': 72, 'Chemistry': 73},
              {'Name': 'Tima Bendar', 'Offense': 67, 'Defense': 71, 'Speed': 72, 'Chemistry': 71},
              {'Name': 'Michaelo Bartulin', 'Offense': 75, 'Defense': 70, 'Speed': 71, 'Chemistry': 72},
              {'Name': 'Colino Smithar', 'Offense': 67, 'Defense': 70, 'Speed': 72, 'Chemistry': 64},
              {'Name': 'Simona Schützan', 'Offense': 65, 'Defense': 69, 'Speed': 69, 'Chemistry': 71},
              {'Name': 'Benu Stadldunov', 'Offense': 66, 'Defense': 75, 'Speed': 66, 'Chemistry': 71},
              {'Name': 'Macieji Rutkowstli', 'Offense': 64, 'Defense': 73, 'Speed': 68, 'Chemistry': 73},
              {'Name': 'Hanse Detschin', 'Offense': 63, 'Defense': 75, 'Speed': 66, 'Chemistry': 72},
              {'Name': 'Clemenso Sagven', 'Offense': 63, 'Defense': 71, 'Speed': 67, 'Chemistry': 69},
              {'Name': 'Markusu Freisro', 'Offense': 63, 'Defense': 68, 'Speed': 61, 'Chemistry': 64},
              {'Name': 'Mano Schamsov', 'Offense': 62, 'Defense': 75, 'Speed': 61, 'Chemistry': 69},
              {'Name': 'Luce Münzenik', 'Offense': 59, 'Defense': 71, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Marca Müllar', 'Offense': 59, 'Defense': 71, 'Speed': 60, 'Chemistry': 68},
              {'Name': 'Christiana Schilinar', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Phe Maurar', 'Offense': 84, 'Defense': 88, 'Speed': 89, 'Chemistry': 82},
              {'Name': 'Olego Shilinik', 'Offense': 51, 'Defense': 84, 'Speed': 72, 'Chemistry': 53},
              {'Name': 'Bru Maxwelen', 'Offense': 44, 'Defense': 79, 'Speed': 67, 'Chemistry': 44},
              {'Name': 'Nicke Neufelov', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40}]},
 {'Team': 'Wolfsburg Voltsturm',
  'Momentum': 0,
  'Players': [{'Name': 'Mati Whitinov', 'Offense': 89, 'Defense': 63, 'Speed': 82, 'Chemistry': 68},
              {'Name': 'Ethano Prowovik', 'Offense': 77, 'Defense': 67, 'Speed': 82, 'Chemistry': 72},
              {'Name': 'Jimmya Lambersen', 'Offense': 89, 'Defense': 76, 'Speed': 82, 'Chemistry': 74},
              {'Name': 'Spo Machacven', 'Offense': 85, 'Defense': 67, 'Speed': 79, 'Chemistry': 72},
              {'Name': 'Tylera Gaudetvik', 'Offense': 81, 'Defense': 66, 'Speed': 79, 'Chemistry': 70},
              {'Name': 'Fabio Pfohlro', 'Offense': 73, 'Defense': 74, 'Speed': 78, 'Chemistry': 76},
              {'Name': 'Matto Choupanin', 'Offense': 80, 'Defense': 67, 'Speed': 75, 'Chemistry': 69},
              {'Name': 'Juliano Chrobven', 'Offense': 75, 'Defense': 73, 'Speed': 75, 'Chemistry': 77},
              {'Name': 'Justinu Fesik', 'Offense': 74, 'Defense': 76, 'Speed': 74, 'Chemistry': 75},
              {'Name': 'Juliano Melchiovik', 'Offense': 71, 'Defense': 75, 'Speed': 74, 'Chemistry': 76},
              {'Name': 'Jacobe Hayhursan', 'Offense': 75, 'Defense': 68, 'Speed': 73, 'Chemistry': 69},
              {'Name': 'Robu Lynchen', 'Offense': 72, 'Defense': 62, 'Speed': 72, 'Chemistry': 66},
              {'Name': 'Luisa Schinktli', 'Offense': 70, 'Defense': 63, 'Speed': 72, 'Chemistry': 66},
              {'Name': 'Keate Thompov', 'Offense': 67, 'Defense': 73, 'Speed': 73, 'Chemistry': 76},
              {'Name': 'Jimmya Martinovlek', 'Offense': 63, 'Defense': 69, 'Speed': 70, 'Chemistry': 73},
              {'Name': 'Time Ruckdäschlek', 'Offense': 65, 'Defense': 70, 'Speed': 69, 'Chemistry': 74},
              {'Name': 'Svenu Zieglven', 'Offense': 64, 'Defense': 64, 'Speed': 66, 'Chemistry': 66},
              {'Name': 'Janika Mösvik', 'Offense': 62, 'Defense': 71, 'Speed': 65, 'Chemistry': 72},
              {'Name': 'Björnu Kruppen', 'Offense': 61, 'Defense': 69, 'Speed': 63, 'Chemistry': 68},
              {'Name': 'Robino Vebov', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Tilu Raabov', 'Offense': 60, 'Defense': 74, 'Speed': 54, 'Chemistry': 63},
              {'Name': 'Jule Ramosinov', 'Offense': 60, 'Defense': 70, 'Speed': 64, 'Chemistry': 70},
              {'Name': 'Lucase Dumontsen', 'Offense': 60, 'Defense': 70, 'Speed': 66, 'Chemistry': 72},
              {'Name': 'Lea Hafenrichtik', 'Offense': 59, 'Defense': 69, 'Speed': 66, 'Chemistry': 73},
              {'Name': 'Dustino Strahlmeiar', 'Offense': 80, 'Defense': 87, 'Speed': 87, 'Chemistry': 75},
              {'Name': 'Hannibalu Weitzdunov', 'Offense': 69, 'Defense': 85, 'Speed': 80, 'Chemistry': 63}]},
 {'Team': 'Whiteout Berlin',
  'Momentum': 0,
  'Players': [{'Name': 'Fri Tiffelar', 'Offense': 84, 'Defense': 76, 'Speed': 87, 'Chemistry': 78},
              {'Name': 'Tyi Ronninsen', 'Offense': 97, 'Defense': 78, 'Speed': 86, 'Chemistry': 79},
              {'Name': 'Leonharda Pfödersen', 'Offense': 87, 'Defense': 74, 'Speed': 82, 'Chemistry': 77},
              {'Name': 'Liamu Kirkven', 'Offense': 80, 'Defense': 72, 'Speed': 80, 'Chemistry': 76},
              {'Name': 'Markusu Vikingstovik', 'Offense': 86, 'Defense': 81, 'Speed': 79, 'Chemistry': 82},
              {'Name': 'Andi Edtli', 'Offense': 80, 'Defense': 73, 'Speed': 79, 'Chemistry': 76},
              {'Name': 'Ericu Mikik', 'Offense': 72, 'Defense': 84, 'Speed': 75, 'Chemistry': 82},
              {'Name': 'Leane Bergen', 'Offense': 69, 'Defense': 68, 'Speed': 75, 'Chemistry': 73},
              {'Name': 'Jonasu Müllar', 'Offense': 70, 'Defense': 67, 'Speed': 74, 'Chemistry': 72},
              {'Name': 'Mita Reinknik', 'Offense': 68, 'Defense': 74, 'Speed': 71, 'Chemistry': 75},
              {'Name': 'Mano Wiederik', 'Offense': 69, 'Defense': 70, 'Speed': 72, 'Chemistry': 74},
              {'Name': 'Blainu Byronvik', 'Offense': 70, 'Defense': 72, 'Speed': 71, 'Chemistry': 68},
              {'Name': 'Yannicku Veillenik', 'Offense': 69, 'Defense': 56, 'Speed': 69, 'Chemistry': 64},
              {'Name': 'Marcu Noebellek', 'Offense': 69, 'Defense': 75, 'Speed': 65, 'Chemistry': 70},
              {'Name': 'Korbiniani Geibov', 'Offense': 68, 'Defense': 73, 'Speed': 66, 'Chemistry': 69},
              {'Name': 'Pata Khodorenovik', 'Offense': 68, 'Defense': 69, 'Speed': 69, 'Chemistry': 62},
              {'Name': 'Adamo Smithar', 'Offense': 63, 'Defense': 69, 'Speed': 69, 'Chemistry': 73},
              {'Name': 'Lestera Lancastinov', 'Offense': 65, 'Defense': 74, 'Speed': 63, 'Chemistry': 67},
              {'Name': 'Norwinu Panochdunov', 'Offense': 61, 'Defense': 69, 'Speed': 68, 'Chemistry': 72},
              {'Name': 'Jeu Denik', 'Offense': 64, 'Defense': 67, 'Speed': 60, 'Chemistry': 61},
              {'Name': 'Ericu Hördlinov', 'Offense': 61, 'Defense': 69, 'Speed': 68, 'Chemistry': 73},
              {'Name': 'Markusu Niemeläinan', 'Offense': 59, 'Defense': 71, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Moritzi Kretzschmnik', 'Offense': 59, 'Defense': 71, 'Speed': 58, 'Chemistry': 66},
              {'Name': 'Mateju Ledenov', 'Offense': 59, 'Defense': 71, 'Speed': 66, 'Chemistry': 74},
              {'Name': 'Jake Hildebrro', 'Offense': 95, 'Defense': 88, 'Speed': 94, 'Chemistry': 91},
              {'Name': 'Jonasu Stettmov', 'Offense': 55, 'Defense': 81, 'Speed': 73, 'Chemistry': 51}]}]

sued_teams = [{'Team': 'Augsburg Ferox',
  'Momentum': 0,
  'Players': [{'Name': 'Ale Greniov', 'Offense': 92, 'Defense': 72, 'Speed': 86, 'Chemistry': 76},
              {'Name': 'Ale Blankov', 'Offense': 87, 'Defense': 78, 'Speed': 84, 'Chemistry': 80},
              {'Name': 'Dono Busdekvik', 'Offense': 91, 'Defense': 68, 'Speed': 80, 'Chemistry': 73},
              {'Name': 'Rileyu Damiansen', 'Offense': 89, 'Defense': 67, 'Speed': 80, 'Chemistry': 71},
              {'Name': 'Tima Wohlgemtto', 'Offense': 81, 'Defense': 76, 'Speed': 79, 'Chemistry': 78},
              {'Name': 'Codye Kunyken', 'Offense': 79, 'Defense': 67, 'Speed': 79, 'Chemistry': 72},
              {'Name': 'Kyli Mayhewtli', 'Offense': 75, 'Defense': 77, 'Speed': 77, 'Chemistry': 78},
              {'Name': 'Madisoni Boweydunov', 'Offense': 72, 'Defense': 79, 'Speed': 77, 'Chemistry': 79},
              {'Name': 'Thoma Schemitsik', 'Offense': 70, 'Defense': 63, 'Speed': 76, 'Chemistry': 70},
              {'Name': 'Anthonyu Louisovik', 'Offense': 76, 'Defense': 73, 'Speed': 74, 'Chemistry': 72},
              {'Name': 'Josephu Cramarosan', 'Offense': 70, 'Defense': 68, 'Speed': 70, 'Chemistry': 67},
              {'Name': 'Ryani Buttonan', 'Offense': 65, 'Defense': 62, 'Speed': 72, 'Chemistry': 69},
              {'Name': 'Floriani Eliasov', 'Offense': 66, 'Defense': 69, 'Speed': 70, 'Chemistry': 72},
              {'Name': 'Enra Moralin', 'Offense': 64, 'Defense': 69, 'Speed': 69, 'Chemistry': 71},
              {'Name': 'Christiana Hankov', 'Offense': 64, 'Defense': 71, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Moritzi Eliasov', 'Offense': 64, 'Defense': 71, 'Speed': 66, 'Chemistry': 71},
              {'Name': 'Leona Lindlek', 'Offense': 63, 'Defense': 64, 'Speed': 68, 'Chemistry': 70},
              {'Name': 'Maximiliana Rennov', 'Offense': 61, 'Defense': 64, 'Speed': 69, 'Chemistry': 71},
              {'Name': 'Thoma Trevelyov', 'Offense': 61, 'Defense': 72, 'Speed': 61, 'Chemistry': 65},
              {'Name': 'Lirono Pellizzvik', 'Offense': 59, 'Defense': 72, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Luce Tostar', 'Offense': 60, 'Defense': 73, 'Speed': 56, 'Chemistry': 64},
              {'Name': 'Moritzi Wirthnik', 'Offense': 59, 'Defense': 70, 'Speed': 57, 'Chemistry': 64},
              {'Name': 'Sebu Zwicklov', 'Offense': 60, 'Defense': 74, 'Speed': 58, 'Chemistry': 66},
              {'Name': 'Fabi Pilen', 'Offense': 59, 'Defense': 72, 'Speed': 62, 'Chemistry': 70},
              {'Name': 'Michaelo Garteov', 'Offense': 79, 'Defense': 87, 'Speed': 87, 'Chemistry': 70},
              {'Name': 'Peytone Jonessen', 'Offense': 76, 'Defense': 83, 'Speed': 85, 'Chemistry': 68}]},
 {'Team': 'Landshut Lichtkern',
  'Momentum': 0,
  'Players': [{'Name': 'Tore Immvik', 'Offense': 97, 'Defense': 66, 'Speed': 89, 'Chemistry': 70},
              {'Name': 'Toba Lindvik', 'Offense': 92, 'Defense': 71, 'Speed': 83, 'Chemistry': 72},
              {'Name': 'Trevu Goochan', 'Offense': 92, 'Defense': 83, 'Speed': 83, 'Chemistry': 80},
              {'Name': 'Davida Elsninov', 'Offense': 80, 'Defense': 75, 'Speed': 80, 'Chemistry': 76},
              {'Name': 'Wadi Bergmtto', 'Offense': 76, 'Defense': 70, 'Speed': 80, 'Chemistry': 72},
              {'Name': 'Davida Stiellek', 'Offense': 83, 'Defense': 69, 'Speed': 79, 'Chemistry': 70},
              {'Name': 'Stanislave Dietzlek', 'Offense': 76, 'Defense': 77, 'Speed': 76, 'Chemistry': 76},
              {'Name': 'Jesso Koskenkornik', 'Offense': 82, 'Defense': 82, 'Speed': 76, 'Chemistry': 80},
              {'Name': 'Yannicku Wenzsen', 'Offense': 74, 'Defense': 69, 'Speed': 73, 'Chemistry': 70},
              {'Name': 'Simona Seidlar', 'Offense': 70, 'Defense': 74, 'Speed': 72, 'Chemistry': 73},
              {'Name': 'Martine Hasovik', 'Offense': 67, 'Defense': 72, 'Speed': 72, 'Chemistry': 73},
              {'Name': 'Toba Schwardunov', 'Offense': 69, 'Defense': 66, 'Speed': 70, 'Chemistry': 68},
              {'Name': 'Eliase Lindnov', 'Offense': 67, 'Defense': 67, 'Speed': 66, 'Chemistry': 66},
              {'Name': 'Sei Parkdunov', 'Offense': 66, 'Defense': 67, 'Speed': 68, 'Chemistry': 71},
              {'Name': 'Andi Schwardunov', 'Offense': 65, 'Defense': 76, 'Speed': 65, 'Chemistry': 71},
              {'Name': 'Oliveri Stümpsen', 'Offense': 64, 'Defense': 69, 'Speed': 64, 'Chemistry': 67},
              {'Name': 'Juliano Kornelllek', 'Offense': 64, 'Defense': 75, 'Speed': 65, 'Chemistry': 72},
              {'Name': 'Jakobu Mayenschtto', 'Offense': 64, 'Defense': 65, 'Speed': 67, 'Chemistry': 69},
              {'Name': 'Finni Seriktto', 'Offense': 63, 'Defense': 63, 'Speed': 67, 'Chemistry': 67},
              {'Name': 'Linusa Brandlik', 'Offense': 65, 'Defense': 76, 'Speed': 67, 'Chemistry': 66},
              {'Name': 'Ale Derschven', 'Offense': 63, 'Defense': 74, 'Speed': 60, 'Chemistry': 66},
              {'Name': 'Pasco Stecknik', 'Offense': 62, 'Defense': 74, 'Speed': 60, 'Chemistry': 66},
              {'Name': 'Luisa Scheibengrablek', 'Offense': 62, 'Defense': 63, 'Speed': 60, 'Chemistry': 62},
              {'Name': 'Dominiki Grossnik', 'Offense': 61, 'Defense': 74, 'Speed': 62, 'Chemistry': 70},
              {'Name': 'Lukasu Gaustto', 'Offense': 60, 'Defense': 74, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Marcu Taberten', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Maximiliana Oswalddunov', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Jonasu Langlek', 'Offense': 70, 'Defense': 86, 'Speed': 82, 'Chemistry': 65},
              {'Name': 'Phe Dietldunov', 'Offense': 72, 'Defense': 87, 'Speed': 84, 'Chemistry': 68},
              {'Name': 'Daniele Henten', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40}]},
 {'Team': 'München FluxBullen',
  'Momentum': 0,
  'Players': [{'Name': 'Taro Hirosdunov', 'Offense': 87, 'Defense': 80, 'Speed': 86, 'Chemistry': 80},
              {'Name': 'Adamo Brooksovik', 'Offense': 81, 'Defense': 71, 'Speed': 79, 'Chemistry': 75},
              {'Name': 'Christophera DeSousovik', 'Offense': 84, 'Defense': 58, 'Speed': 80, 'Chemistry': 66},
              {'Name': 'Yasino Ehlizov', 'Offense': 78, 'Defense': 74, 'Speed': 79, 'Chemistry': 76},
              {'Name': 'Toba Riedinov', 'Offense': 83, 'Defense': 70, 'Speed': 77, 'Chemistry': 71},
              {'Name': 'Veita Oswalddunov', 'Offense': 78, 'Defense': 72, 'Speed': 76, 'Chemistry': 76},
              {'Name': 'Markusu Eisenschmlek', 'Offense': 75, 'Defense': 74, 'Speed': 74, 'Chemistry': 75},
              {'Name': 'Gabo Fontaintto', 'Offense': 73, 'Defense': 67, 'Speed': 74, 'Chemistry': 69},
              {'Name': 'Villa Pokkvik', 'Offense': 70, 'Defense': 69, 'Speed': 75, 'Chemistry': 73},
              {'Name': 'Bradya Ferguinov', 'Offense': 75, 'Defense': 57, 'Speed': 73, 'Chemistry': 66},
              {'Name': 'Jeri McKennven', 'Offense': 72, 'Defense': 69, 'Speed': 72, 'Chemistry': 73},
              {'Name': 'Pata Hagik', 'Offense': 71, 'Defense': 74, 'Speed': 73, 'Chemistry': 76},
              {'Name': 'Ryani Murphyro', 'Offense': 71, 'Defense': 70, 'Speed': 72, 'Chemistry': 70},
              {'Name': 'Dille Heatheringttto', 'Offense': 68, 'Defense': 78, 'Speed': 72, 'Chemistry': 78},
              {'Name': 'Maximiliana Kastnlek', 'Offense': 68, 'Defense': 56, 'Speed': 71, 'Chemistry': 65},
              {'Name': 'Fabio Wagnov', 'Offense': 64, 'Defense': 71, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Phe Krenindunov', 'Offense': 64, 'Defense': 71, 'Speed': 67, 'Chemistry': 72},
              {'Name': 'Konradu Abeltshausdunov', 'Offense': 61, 'Defense': 72, 'Speed': 68, 'Chemistry': 74},
              {'Name': 'Maximiliana Daubndunov', 'Offense': 61, 'Defense': 60, 'Speed': 62, 'Chemistry': 61},
              {'Name': 'Phe Sinnov', 'Offense': 60, 'Defense': 72, 'Speed': 66, 'Chemistry': 73},
              {'Name': 'Niki Heiglik', 'Offense': 60, 'Defense': 72, 'Speed': 58, 'Chemistry': 67},
              {'Name': 'Ria Kaisdunov', 'Offense': 59, 'Defense': 74, 'Speed': 60, 'Chemistry': 69},
              {'Name': 'Anto Bibeaovik', 'Offense': 47, 'Defense': 84, 'Speed': 70, 'Chemistry': 46},
              {'Name': 'Mathiaso Niederen', 'Offense': 85, 'Defense': 86, 'Speed': 87, 'Chemistry': 85},
              {'Name': 'Simona Wolfov', 'Offense': 54, 'Defense': 81, 'Speed': 72, 'Chemistry': 51}]},
 {'Team': 'Mannheim Ventus',
  'Momentum': 0,
  'Players': [{'Name': 'Nicolasa Mattinlek', 'Offense': 88, 'Defense': 82, 'Speed': 83, 'Chemistry': 81},
              {'Name': 'Marcu Michaelsen', 'Offense': 80, 'Defense': 74, 'Speed': 83, 'Chemistry': 77},
              {'Name': 'Anthonyu Grecan', 'Offense': 84, 'Defense': 75, 'Speed': 81, 'Chemistry': 78},
              {'Name': 'Matthiasu Plachtven', 'Offense': 75, 'Defense': 73, 'Speed': 79, 'Chemistry': 76},
              {'Name': 'Justinu Schützan', 'Offense': 82, 'Defense': 73, 'Speed': 79, 'Chemistry': 75},
              {'Name': 'Kristianu Reichlek', 'Offense': 81, 'Defense': 77, 'Speed': 78, 'Chemistry': 78},
              {'Name': 'Zaco Solowlek', 'Offense': 78, 'Defense': 75, 'Speed': 76, 'Chemistry': 77},
              {'Name': 'Leona Gawankvik', 'Offense': 74, 'Defense': 79, 'Speed': 75, 'Chemistry': 78},
              {'Name': 'Johne Gilmoik', 'Offense': 70, 'Defense': 71, 'Speed': 76, 'Chemistry': 74},
              {'Name': 'Krise Bennettto', 'Offense': 76, 'Defense': 70, 'Speed': 74, 'Chemistry': 76},
              {'Name': 'Maximiliana Heimov', 'Offense': 76, 'Defense': 74, 'Speed': 74, 'Chemistry': 77},
              {'Name': 'Lukasu Kälbldunov', 'Offense': 69, 'Defense': 85, 'Speed': 72, 'Chemistry': 81},
              {'Name': 'Tome Kühnhacan', 'Offense': 70, 'Defense': 78, 'Speed': 73, 'Chemistry': 72},
              {'Name': 'Ale Ehlven', 'Offense': 67, 'Defense': 78, 'Speed': 69, 'Chemistry': 76},
              {'Name': 'Luko Espositov', 'Offense': 66, 'Defense': 69, 'Speed': 68, 'Chemistry': 69},
              {'Name': 'Yannicku Proskov', 'Offense': 68, 'Defense': 79, 'Speed': 70, 'Chemistry': 80},
              {'Name': 'Maxe Penkininov', 'Offense': 66, 'Defense': 74, 'Speed': 65, 'Chemistry': 71},
              {'Name': 'Ericu Ubtto', 'Offense': 64, 'Defense': 66, 'Speed': 65, 'Chemistry': 68},
              {'Name': 'Dani Renoufin', 'Offense': 61, 'Defense': 81, 'Speed': 69, 'Chemistry': 80},
              {'Name': 'Haydeno Shawin', 'Offense': 62, 'Defense': 73, 'Speed': 64, 'Chemistry': 72},
              {'Name': 'Colino Schlenkik', 'Offense': 59, 'Defense': 70, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Nicke Mählar', 'Offense': 59, 'Defense': 74, 'Speed': 55, 'Chemistry': 65},
              {'Name': 'Toba Fohrlven', 'Offense': 59, 'Defense': 66, 'Speed': 66, 'Chemistry': 71},
              {'Name': 'Maximiliana Franzrnik', 'Offense': 82, 'Defense': 89, 'Speed': 88, 'Chemistry': 79},
              {'Name': 'Johano Mattsik', 'Offense': 67, 'Defense': 88, 'Speed': 81, 'Chemistry': 66}]},
 {'Team': 'Novadelta Panther',
  'Momentum': 0,
  'Players': [{'Name': 'Rilan Barvik', 'Offense': 99, 'Defense': 82, 'Speed': 91, 'Chemistry': 83},
              {'Name': 'Mils Powlek', 'Offense': 98, 'Defense': 75, 'Speed': 88, 'Chemistry': 79},
              {'Name': 'Aleks Bretan', 'Offense': 87, 'Defense': 90, 'Speed': 86, 'Chemistry': 85},
              {'Name': 'Dano Schmolik', 'Offense': 90, 'Defense': 80, 'Speed': 83, 'Chemistry': 80},
              {'Name': 'Ken Agostinov', 'Offense': 88, 'Defense': 80, 'Speed': 83, 'Chemistry': 80},
              {'Name': 'Rileyu Sheentli', 'Offense': 79, 'Defense': 71, 'Speed': 79, 'Chemistry': 73},
              {'Name': 'Abbo Girdunov', 'Offense': 80, 'Defense': 78, 'Speed': 77, 'Chemistry': 77},
              {'Name': 'Peteru Abbandoninov', 'Offense': 78, 'Defense': 79, 'Speed': 78, 'Chemistry': 79},
              {'Name': 'Leo Hütten', 'Offense': 75, 'Defense': 85, 'Speed': 78, 'Chemistry': 82},
              {'Name': 'Morgon Elvik', 'Offense': 75, 'Defense': 80, 'Speed': 76, 'Chemistry': 78},
              {'Name': 'Aust Keaten', 'Offense': 76, 'Defense': 78, 'Speed': 76, 'Chemistry': 80},
              {'Name': 'Filip Krausen', 'Offense': 75, 'Defense': 56, 'Speed': 74, 'Chemistry': 66},
              {'Name': 'Dan Pietto', 'Offense': 73, 'Defense': 78, 'Speed': 75, 'Chemistry': 79},
              {'Name': 'Sam Ruvek', 'Offense': 69, 'Defense': 81, 'Speed': 73, 'Chemistry': 79},
              {'Name': 'Edwin Tropov', 'Offense': 69, 'Defense': 69, 'Speed': 70, 'Chemistry': 73},
              {'Name': 'Philu RosaPrtli', 'Offense': 65, 'Defense': 77, 'Speed': 68, 'Chemistry': 73},
              {'Name': 'Johan Krausen', 'Offense': 64, 'Defense': 71, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Kris Jandro', 'Offense': 64, 'Defense': 56, 'Speed': 66, 'Chemistry': 61},
              {'Name': 'Jakina Smallwnik', 'Offense': 63, 'Defense': 66, 'Speed': 62, 'Chemistry': 64},
              {'Name': 'Dominiki Zerhocin', 'Offense': 59, 'Defense': 72, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Lukasu Jungovik1', 'Offense': 59, 'Defense': 72, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Nicolasa Schindllek', 'Offense': 60, 'Defense': 74, 'Speed': 54, 'Chemistry': 63},
              {'Name': 'Petr Spornik', 'Offense': 59, 'Defense': 70, 'Speed': 58, 'Chemistry': 65},
              {'Name': 'Sam Kharbintli', 'Offense': 60, 'Defense': 64, 'Speed': 60, 'Chemistry': 65},
              {'Name': 'Luka Hauven', 'Offense': 60, 'Defense': 73, 'Speed': 63, 'Chemistry': 71},
              {'Name': 'Niko Pertanov', 'Offense': 42, 'Defense': 93, 'Speed': 71, 'Chemistry': 43},
              {'Name': 'Devon Willark', 'Offense': 79, 'Defense': 86, 'Speed': 85, 'Chemistry': 75},
              {'Name': 'Bret Brokan', 'Offense': 66, 'Defense': 85, 'Speed': 78, 'Chemistry': 66}]},
 {'Team': 'Nürnberg Eistiger',
  'Momentum': 0,
  'Players': [{'Name': 'Evane Barrattto', 'Offense': 86, 'Defense': 70, 'Speed': 88, 'Chemistry': 75},
              {'Name': 'Samueli DoveMcFalan', 'Offense': 89, 'Defense': 73, 'Speed': 80, 'Chemistry': 77},
              {'Name': 'Thoma Heiglik', 'Offense': 85, 'Defense': 83, 'Speed': 79, 'Chemistry': 83},
              {'Name': 'Colu Maiar', 'Offense': 86, 'Defense': 75, 'Speed': 80, 'Chemistry': 73},
              {'Name': 'Cha Gerardar', 'Offense': 77, 'Defense': 62, 'Speed': 78, 'Chemistry': 69},
              {'Name': 'Tylera Spezitto', 'Offense': 82, 'Defense': 67, 'Speed': 77, 'Chemistry': 71},
              {'Name': 'Grege Meirelvik', 'Offense': 69, 'Defense': 67, 'Speed': 75, 'Chemistry': 71},
              {'Name': 'Bretta Murraytto', 'Offense': 77, 'Defense': 75, 'Speed': 75, 'Chemistry': 69},
              {'Name': 'Owene Headricik', 'Offense': 71, 'Defense': 65, 'Speed': 74, 'Chemistry': 70},
              {'Name': 'Codye Haiskanov', 'Offense': 70, 'Defense': 60, 'Speed': 73, 'Chemistry': 68},
              {'Name': 'Constantinu Braunovik', 'Offense': 70, 'Defense': 75, 'Speed': 72, 'Chemistry': 75},
              {'Name': 'Jule Karrsen', 'Offense': 67, 'Defense': 75, 'Speed': 73, 'Chemistry': 76},
              {'Name': 'Jakobu Webik', 'Offense': 65, 'Defense': 82, 'Speed': 72, 'Chemistry': 81},
              {'Name': 'Romane Kechtov', 'Offense': 68, 'Defense': 67, 'Speed': 70, 'Chemistry': 69},
              {'Name': 'Marcuse Webik', 'Offense': 66, 'Defense': 71, 'Speed': 70, 'Chemistry': 75},
              {'Name': 'Justu Böttninov', 'Offense': 64, 'Defense': 73, 'Speed': 70, 'Chemistry': 76},
              {'Name': 'Williame Grabtto', 'Offense': 69, 'Defense': 64, 'Speed': 67, 'Chemistry': 61},
              {'Name': 'Eugeni Alanovik', 'Offense': 62, 'Defense': 70, 'Speed': 64, 'Chemistry': 66},
              {'Name': 'Jakobu Ustorfin', 'Offense': 61, 'Defense': 69, 'Speed': 61, 'Chemistry': 65},
              {'Name': 'Josefa Ehamtli', 'Offense': 61, 'Defense': 61, 'Speed': 64, 'Chemistry': 63},
              {'Name': 'Luisa Üffingvik', 'Offense': 61, 'Defense': 69, 'Speed': 65, 'Chemistry': 69},
              {'Name': 'Maximiliana Merklov', 'Offense': 59, 'Defense': 72, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Time Bakosan', 'Offense': 60, 'Defense': 74, 'Speed': 55, 'Chemistry': 63},
              {'Name': 'Nikla Treutlven', 'Offense': 80, 'Defense': 86, 'Speed': 88, 'Chemistry': 71},
              {'Name': 'Evane Fitzpatrin', 'Offense': 72, 'Defense': 85, 'Speed': 82, 'Chemistry': 68}]},
 {'Team': 'Regensburg Pulse',
  'Momentum': 0,
  'Players': [{'Name': 'Davida Morleylek', 'Offense': 82, 'Defense': 74, 'Speed': 80, 'Chemistry': 71},
              {'Name': 'Pierri Pretvik', 'Offense': 81, 'Defense': 65, 'Speed': 77, 'Chemistry': 67},
              {'Name': 'Coreye Trivinov', 'Offense': 79, 'Defense': 62, 'Speed': 77, 'Chemistry': 64},
              {'Name': 'Kevine Slezakdunov', 'Offense': 75, 'Defense': 77, 'Speed': 76, 'Chemistry': 74},
              {'Name': 'Samueli Payeuren', 'Offense': 74, 'Defense': 70, 'Speed': 74, 'Chemistry': 73},
              {'Name': 'Bryco Kindopro', 'Offense': 75, 'Defense': 74, 'Speed': 73, 'Chemistry': 73},
              {'Name': 'Jakobu Webik', 'Offense': 70, 'Defense': 77, 'Speed': 72, 'Chemistry': 75},
              {'Name': 'Constantinu Ontlinov', 'Offense': 76, 'Defense': 72, 'Speed': 71, 'Chemistry': 68},
              {'Name': 'Niko Gajovsknik', 'Offense': 69, 'Defense': 67, 'Speed': 71, 'Chemistry': 70},
              {'Name': 'Alexe Berardinelik', 'Offense': 69, 'Defense': 73, 'Speed': 69, 'Chemistry': 69},
              {'Name': 'Yumu Grimmov', 'Offense': 66, 'Defense': 60, 'Speed': 69, 'Chemistry': 65},
              {'Name': 'Donáti Pétlek', 'Offense': 68, 'Defense': 72, 'Speed': 68, 'Chemistry': 71},
              {'Name': 'Pata Demetzar', 'Offense': 62, 'Defense': 67, 'Speed': 65, 'Chemistry': 67},
              {'Name': 'Seano Gilestto', 'Offense': 62, 'Defense': 70, 'Speed': 65, 'Chemistry': 70},
              {'Name': 'Guillauma Naudlek', 'Offense': 62, 'Defense': 66, 'Speed': 66, 'Chemistry': 68},
              {'Name': 'Ale Angaran', 'Offense': 62, 'Defense': 68, 'Speed': 66, 'Chemistry': 70},
              {'Name': 'Mara Baudunov', 'Offense': 61, 'Defense': 76, 'Speed': 62, 'Chemistry': 71},
              {'Name': 'Nicke Mählar', 'Offense': 61, 'Defense': 67, 'Speed': 63, 'Chemistry': 67},
              {'Name': 'Maximiliana Merklov', 'Offense': 61, 'Defense': 72, 'Speed': 64, 'Chemistry': 71},
              {'Name': 'Pasco Zerresvik', 'Offense': 61, 'Defense': 66, 'Speed': 65, 'Chemistry': 69},
              {'Name': 'Mateju Giesltto', 'Offense': 60, 'Defense': 68, 'Speed': 55, 'Chemistry': 62},
              {'Name': 'Marksi Jirgensdunov', 'Offense': 60, 'Defense': 74, 'Speed': 58, 'Chemistry': 66},
              {'Name': 'Lukasu Kriegsen', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Juliano Elssen', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Viktore Buchnik', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Pasco Aquinen', 'Offense': 60, 'Defense': 74, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Jonasu Neffindunov', 'Offense': 89, 'Defense': 93, 'Speed': 93, 'Chemistry': 84},
              {'Name': 'Konradu Fiedlsen', 'Offense': 48, 'Defense': 82, 'Speed': 71, 'Chemistry': 47},
              {'Name': 'Colu Danielsmeiov', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40}]},
 {'Team': 'Ravensburg Zenit Falken',
  'Momentum': 0,
  'Players': [{'Name': 'Marki Rasselnik', 'Offense': 90, 'Defense': 76, 'Speed': 81, 'Chemistry': 77},
              {'Name': 'Robbii Czarnvik', 'Offense': 85, 'Defense': 58, 'Speed': 81, 'Chemistry': 67},
              {'Name': 'Eriki Karlsdunov', 'Offense': 82, 'Defense': 71, 'Speed': 80, 'Chemistry': 72},
              {'Name': 'Ale Voyinov', 'Offense': 77, 'Defense': 52, 'Speed': 74, 'Chemistry': 63},
              {'Name': 'Simona Sezemsktli', 'Offense': 72, 'Defense': 81, 'Speed': 73, 'Chemistry': 78},
              {'Name': 'Nicu Lattvik', 'Offense': 75, 'Defense': 61, 'Speed': 72, 'Chemistry': 66},
              {'Name': 'Marvino Schmidtto', 'Offense': 68, 'Defense': 64, 'Speed': 72, 'Chemistry': 67},
              {'Name': 'Thoma Reichlek', 'Offense': 65, 'Defense': 71, 'Speed': 69, 'Chemistry': 70},
              {'Name': 'Aleca Ahlrotvik', 'Offense': 68, 'Defense': 64, 'Speed': 68, 'Chemistry': 65},
              {'Name': 'Louise Lattvik', 'Offense': 65, 'Defense': 64, 'Speed': 69, 'Chemistry': 66},
              {'Name': 'Luka Hauven', 'Offense': 68, 'Defense': 73, 'Speed': 66, 'Chemistry': 67},
              {'Name': 'Fabio Sartven', 'Offense': 66, 'Defense': 68, 'Speed': 67, 'Chemistry': 70},
              {'Name': 'Denise Pfaffengen', 'Offense': 63, 'Defense': 77, 'Speed': 67, 'Chemistry': 74},
              {'Name': 'Juliano Eichinglek', 'Offense': 63, 'Defense': 69, 'Speed': 68, 'Chemistry': 71},
              {'Name': 'Phe Massovik', 'Offense': 63, 'Defense': 65, 'Speed': 68, 'Chemistry': 69},
              {'Name': 'Mateju Mrazekdunov', 'Offense': 63, 'Defense': 72, 'Speed': 63, 'Chemistry': 66},
              {'Name': 'Ryani Odudar', 'Offense': 62, 'Defense': 64, 'Speed': 67, 'Chemistry': 68},
              {'Name': 'Niki Kesslinov', 'Offense': 63, 'Defense': 50, 'Speed': 63, 'Chemistry': 59},
              {'Name': 'Flora Ketteren', 'Offense': 62, 'Defense': 69, 'Speed': 61, 'Chemistry': 65},
              {'Name': 'Lukasu Jungovik', 'Offense': 61, 'Defense': 60, 'Speed': 63, 'Chemistry': 63},
              {'Name': 'Leona Sivicen', 'Offense': 60, 'Defense': 74, 'Speed': 54, 'Chemistry': 63},
              {'Name': 'Nicolasa Schindllek', 'Offense': 60, 'Defense': 75, 'Speed': 55, 'Chemistry': 65},
              {'Name': 'Jano Wieszinslek', 'Offense': 59, 'Defense': 67, 'Speed': 56, 'Chemistry': 62},
              {'Name': 'Jonasu Müllar', 'Offense': 59, 'Defense': 70, 'Speed': 59, 'Chemistry': 66},
              {'Name': 'Anso Gergik', 'Offense': 60, 'Defense': 72, 'Speed': 63, 'Chemistry': 70},
              {'Name': 'Edwin Tropov', 'Offense': 59, 'Defense': 72, 'Speed': 53, 'Chemistry': 62},
              {'Name': 'Ilye Sharipovik', 'Offense': 83, 'Defense': 82, 'Speed': 86, 'Chemistry': 74},
              {'Name': 'Niko Pertanov', 'Offense': 54, 'Defense': 83, 'Speed': 72, 'Chemistry': 53},
              {'Name': 'Philu Gründlar', 'Offense': 41, 'Defense': 93, 'Speed': 70, 'Chemistry': 41},
              {'Name': 'Nica Wiensdunov', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40},
              {'Name': 'Raphaelo Roedinov', 'Offense': 40, 'Defense': 61, 'Speed': 40, 'Chemistry': 40}]},
 {'Team': 'Straubing Forest Tigers',
  'Momentum': 0,
  'Players': [{'Name': 'Marcu Brandtin', 'Offense': 95, 'Defense': 81, 'Speed': 88, 'Chemistry': 79},
              {'Name': 'Nicholasu Hallorar', 'Offense': 94, 'Defense': 82, 'Speed': 84, 'Chemistry': 83},
              {'Name': 'Elisu Hedov', 'Offense': 93, 'Defense': 82, 'Speed': 82, 'Chemistry': 83},
              {'Name': 'Stefane Loibldunov', 'Offense': 80, 'Defense': 71, 'Speed': 82, 'Chemistry': 74},
              {'Name': 'Alexe Greenar', 'Offense': 79, 'Defense': 82, 'Speed': 79, 'Chemistry': 81},
              {'Name': 'Justinu Scottro', 'Offense': 82, 'Defense': 72, 'Speed': 77, 'Chemistry': 76},
              {'Name': 'Tima Fleischtto', 'Offense': 77, 'Defense': 75, 'Speed': 78, 'Chemistry': 78},
              {'Name': 'Danju Leonharik', 'Offense': 74, 'Defense': 77, 'Speed': 78, 'Chemistry': 80},
              {'Name': 'Wadi Alliven', 'Offense': 80, 'Defense': 76, 'Speed': 77, 'Chemistry': 75},
              {'Name': 'Filipi Varejckov', 'Offense': 78, 'Defense': 76, 'Speed': 77, 'Chemistry': 79},
              {'Name': 'Tylera Maddenro', 'Offense': 78, 'Defense': 76, 'Speed': 78, 'Chemistry': 71},
              {'Name': 'Joshe Melnicov', 'Offense': 70, 'Defense': 77, 'Speed': 74, 'Chemistry': 80},
              {'Name': 'Tima Brunnhubinov', 'Offense': 70, 'Defense': 77, 'Speed': 74, 'Chemistry': 80},
              {'Name': 'Zaco Leslinik', 'Offense': 71, 'Defense': 77, 'Speed': 73, 'Chemistry': 73},
              {'Name': 'Adriano Kleintli', 'Offense': 70, 'Defense': 79, 'Speed': 73, 'Chemistry': 79},
              {'Name': 'Nicolasa Beaudan', 'Offense': 69, 'Defense': 79, 'Speed': 73, 'Chemistry': 79},
              {'Name': 'Skyle McKenzvik', 'Offense': 71, 'Defense': 71, 'Speed': 71, 'Chemistry': 73},
              {'Name': 'Marie Zimmerar', 'Offense': 67, 'Defense': 74, 'Speed': 70, 'Chemistry': 74},
              {'Name': 'Stephana Daschnov', 'Offense': 63, 'Defense': 80, 'Speed': 70, 'Chemistry': 80},
              {'Name': 'Linusa Brandlik', 'Offense': 64, 'Defense': 68, 'Speed': 66, 'Chemistry': 70},
              {'Name': 'Michaelo Connollnik', 'Offense': 63, 'Defense': 72, 'Speed': 63, 'Chemistry': 66},
              {'Name': 'Toba Schwardunov', 'Offense': 60, 'Defense': 75, 'Speed': 54, 'Chemistry': 63},
              {'Name': 'Simona Seidlar', 'Offense': 60, 'Defense': 74, 'Speed': 55, 'Chemistry': 64},
              {'Name': 'Henrike Haukelik', 'Offense': 95, 'Defense': 89, 'Speed': 92, 'Chemistry': 99},
              {'Name': 'Floriani Buglov', 'Offense': 51, 'Defense': 81, 'Speed': 71, 'Chemistry': 50}]},
 {'Team': 'Schwenningen Sturmflügel',
  'Momentum': 0,
  'Players': [{'Name': 'Tysono Spinkar', 'Offense': 86, 'Defense': 74, 'Speed': 79, 'Chemistry': 78},
              {'Name': 'Tylora Spinkar', 'Offense': 80, 'Defense': 74, 'Speed': 79, 'Chemistry': 78},
              {'Name': 'Ale Karachinov', 'Offense': 81, 'Defense': 58, 'Speed': 78, 'Chemistry': 68},
              {'Name': 'Kyli Platzov', 'Offense': 72, 'Defense': 62, 'Speed': 78, 'Chemistry': 70},
              {'Name': 'Zachi Senyshyro', 'Offense': 84, 'Defense': 73, 'Speed': 77, 'Chemistry': 74},
              {'Name': 'Ericu Martinstli', 'Offense': 70, 'Defense': 76, 'Speed': 76, 'Chemistry': 77},
              {'Name': 'Jorde Szwarzar', 'Offense': 74, 'Defense': 72, 'Speed': 74, 'Chemistry': 72},
              {'Name': 'Philu Hungereckdunov', 'Offense': 73, 'Defense': 77, 'Speed': 74, 'Chemistry': 77},
              {'Name': 'Daniele OReganovik', 'Offense': 80, 'Defense': 69, 'Speed': 74, 'Chemistry': 66},
              {'Name': 'Thoma Larkinik', 'Offense': 69, 'Defense': 70, 'Speed': 73, 'Chemistry': 74},
              {'Name': 'Alexe Trivellvik', 'Offense': 68, 'Defense': 70, 'Speed': 71, 'Chemistry': 71},
              {'Name': 'Mirke Höfflro', 'Offense': 67, 'Defense': 67, 'Speed': 72, 'Chemistry': 71},
              {'Name': 'Benu Marshaltto', 'Offense': 65, 'Defense': 70, 'Speed': 72, 'Chemistry': 73},
              {'Name': 'Sebu Uvirtli', 'Offense': 66, 'Defense': 64, 'Speed': 71, 'Chemistry': 72},
              {'Name': 'Arko Dziambovik', 'Offense': 68, 'Defense': 73, 'Speed': 69, 'Chemistry': 73},
              {'Name': 'Håkone Häneltik', 'Offense': 63, 'Defense': 68, 'Speed': 69, 'Chemistry': 69},
              {'Name': 'Boazo Basov', 'Offense': 66, 'Defense': 64, 'Speed': 70, 'Chemistry': 71},
              {'Name': 'Philu Feistov', 'Offense': 65, 'Defense': 70, 'Speed': 63, 'Chemistry': 64},
              {'Name': 'Felixe Scheven', 'Offense': 64, 'Defense': 73, 'Speed': 64, 'Chemistry': 69},
              {'Name': 'Nikla Hübndunov', 'Offense': 62, 'Defense': 74, 'Speed': 66, 'Chemistry': 73},
              {'Name': 'Williame Webik', 'Offense': 62, 'Defense': 64, 'Speed': 66, 'Chemistry': 69},
              {'Name': 'Dominiki Bittnlek', 'Offense': 61, 'Defense': 68, 'Speed': 65, 'Chemistry': 70},
              {'Name': 'Tima Gettingsen', 'Offense': 60, 'Defense': 74, 'Speed': 54, 'Chemistry': 63},
              {'Name': 'Nicli Hempinov', 'Offense': 59, 'Defense': 72, 'Speed': 58, 'Chemistry': 66},
              {'Name': 'Joacimi Erikstli', 'Offense': 87, 'Defense': 91, 'Speed': 91, 'Chemistry': 85},
              {'Name': 'Michaelo Bitzven', 'Offense': 64, 'Defense': 85, 'Speed': 79, 'Chemistry': 60}]}]
