# Diese Datei wurde automatisch aus players_rated.json erzeugt.
# Web-Format: kompakte 1-Zeilen-Spielereinträge.

nord_teams = [
{
  "Team": "Bad Nauheim Devils",
  "Momentum": 0,
  "Players": [
    {"Name":"Justinu MacPherar","Number":6,"Position":"D","Offense":84,"Defense":75,"Speed":82,"Chemistry":74},
    {"Name":"Jorde Hickmotik","Number":61,"Position":"F","Offense":89,"Defense":76,"Speed":76,"Chemistry":74},
    {"Name":"Parkera Bowlestto","Number":90,"Position":"F","Offense":74,"Defense":63,"Speed":76,"Chemistry":67},
    {"Name":"Juliano Lautenschlagov","Number":93,"Position":"F","Offense":77,"Defense":71,"Speed":75,"Chemistry":73},
    {"Name":"Andre Biresven","Number":88,"Position":"F","Offense":73,"Defense":64,"Speed":73,"Chemistry":68},
    {"Name":"Justinu Volekinov","Number":55,"Position":"F","Offense":71,"Defense":75,"Speed":73,"Chemistry":73},
    {"Name":"Zachi Kaisdunov","Number":73,"Position":"F","Offense":71,"Defense":65,"Speed":72,"Chemistry":67},
    {"Name":"Davisa Kochik","Number":7,"Position":"F","Offense":69,"Defense":61,"Speed":72,"Chemistry":68},
    {"Name":"Taylori Vausan","Number":19,"Position":"F","Offense":72,"Defense":68,"Speed":70,"Chemistry":66},
    {"Name":"Raphaelo Jakovlov","Number":17,"Position":"F","Offense":68,"Defense":68,"Speed":69,"Chemistry":69},
    {"Name":"Lukasu Ribarov","Number":11,"Position":"F","Offense":66,"Defense":68,"Speed":68,"Chemistry":70},
    {"Name":"Marcu ElSaysen","Number":91,"Position":"F","Offense":63,"Defense":77,"Speed":67,"Chemistry":73},
    {"Name":"Mariusi Erken","Number":23,"Position":"D","Offense":62,"Defense":66,"Speed":67,"Chemistry":69},
    {"Name":"Sebu Bengtsvik","Number":21,"Position":"F","Offense":64,"Defense":76,"Speed":64,"Chemistry":66},
    {"Name":"Garreta Prudenvik","Number":15,"Position":"D","Offense":61,"Defense":67,"Speed":66,"Chemistry":70},
    {"Name":"Phe Kuhneksen","Number":29,"Position":"F","Offense":63,"Defense":66,"Speed":61,"Chemistry":61},
    {"Name":"Simona Gnypov","Number":9,"Position":"D","Offense":62,"Defense":69,"Speed":64,"Chemistry":69},
    {"Name":"Christophera Fischven","Number":58,"Position":"D","Offense":62,"Defense":71,"Speed":62,"Chemistry":67},
    {"Name":"Kevine Handschdunov","Number":34,"Position":"F","Offense":62,"Defense":72,"Speed":65,"Chemistry":71},
    {"Name":"Fabianu Nifosan","Number":78,"Position":"D","Offense":59,"Defense":74,"Speed":54,"Chemistry":64},
    {"Name":"Xavera Tippsen","Number":43,"Position":"D","Offense":59,"Defense":69,"Speed":56,"Chemistry":63},
    {"Name":"Tjarka Kölschov","Number":16,"Position":"D","Offense":59,"Defense":72,"Speed":56,"Chemistry":65},
    {"Name":"Phe Bidoulov","Number":24,"Position":"D","Offense":59,"Defense":76,"Speed":58,"Chemistry":70},
    {"Name":"Rike Gaidven","Number":22,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Pata Seifervik","Number":20,"Position":"D","Offense":59,"Defense":73,"Speed":52,"Chemistry":61},
    {"Name":"Geraldo Kuhnnik","Number":35,"Position":"G","Offense":97,"Defense":91,"Speed":96,"Chemistry":92},
    {"Name":"Finni Becklek","Number":53,"Position":"G","Offense":46,"Defense":74,"Speed":68,"Chemistry":45}
  ]
},
{
  "Team": "Bremerhaven Trident",
  "Momentum": 0,
  "Players": [
    {"Name":"Justinu Büsingsen","Number":76,"Position":"F","Offense":63,"Defense":73,"Speed":64,"Chemistry":68},
    {"Name":"Rayanu Bettahsen","Number":15,"Position":"D","Offense":63,"Defense":80,"Speed":62,"Chemistry":72},
    {"Name":"Bennu Rossmyinov","Number":73,"Position":"F","Offense":82,"Defense":65,"Speed":79,"Chemistry":76},
    {"Name":"Christiana Wejsen","Number":65,"Position":"F","Offense":86,"Defense":54,"Speed":78,"Chemistry":65},
    {"Name":"Andyo Miellek","Number":51,"Position":"F","Offense":78,"Defense":67,"Speed":78,"Chemistry":75},
    {"Name":"Jano Urbasik","Number":9,"Position":"F","Offense":78,"Defense":74,"Speed":78,"Chemistry":72},
    {"Name":"Akite Hirosdunov","Number":2,"Position":"D","Offense":76,"Defense":69,"Speed":77,"Chemistry":71},
    {"Name":"Miha Verlicinov","Number":91,"Position":"F","Offense":78,"Defense":74,"Speed":77,"Chemistry":77},
    {"Name":"Zigi Jeglicen","Number":13,"Position":"F","Offense":76,"Defense":70,"Speed":77,"Chemistry":74},
    {"Name":"Ale Frieov","Number":57,"Position":"F","Offense":76,"Defense":71,"Speed":76,"Chemistry":74},
    {"Name":"Nicolasa Krämmov","Number":21,"Position":"F","Offense":74,"Defense":80,"Speed":76,"Chemistry":82},
    {"Name":"Mati Abttli","Number":42,"Position":"D","Offense":75,"Defense":74,"Speed":75,"Chemistry":76},
    {"Name":"Ludwu Byströov","Number":17,"Position":"D","Offense":72,"Defense":79,"Speed":74,"Chemistry":79},
    {"Name":"Maxe Görtzik","Number":23,"Position":"F","Offense":68,"Defense":74,"Speed":73,"Chemistry":76},
    {"Name":"Rossa Mauerven","Number":14,"Position":"F","Offense":72,"Defense":69,"Speed":71,"Chemistry":74},
    {"Name":"Coltu Conradtli","Number":79,"Position":"F","Offense":67,"Defense":71,"Speed":69,"Chemistry":66},
    {"Name":"Nicholasu Jenvik","Number":48,"Position":"D","Offense":66,"Defense":65,"Speed":69,"Chemistry":66},
    {"Name":"Phe Bruggissik","Number":72,"Position":"D","Offense":68,"Defense":64,"Speed":68,"Chemistry":64},
    {"Name":"Vlo Emingik","Number":22,"Position":"D","Offense":67,"Defense":66,"Speed":69,"Chemistry":70},
    {"Name":"Nine Kindik","Number":8,"Position":"F","Offense":63,"Defense":69,"Speed":69,"Chemistry":72},
    {"Name":"Maxima Rauschov","Number":53,"Position":"D","Offense":60,"Defense":72,"Speed":68,"Chemistry":75},
    {"Name":"Fabianu Herrinov","Number":25,"Position":"F","Offense":62,"Defense":66,"Speed":63,"Chemistry":66},
    {"Name":"Kristersi Gudlevskar","Number":30,"Position":"G","Offense":61,"Defense":87,"Speed":78,"Chemistry":58},
    {"Name":"Jule Hudacinov","Number":33,"Position":"G","Offense":89,"Defense":85,"Speed":91,"Chemistry":78},
    {"Name":"Leona Hungereckdunov","Number":27,"Position":"G","Offense":68,"Defense":83,"Speed":80,"Chemistry":65}
  ]
},
{
  "Team": "Düsseldorf Aurora",
  "Momentum": 0,
  "Players": [
    {"Name":"Yushirohe Hiranik","Number":91,"Position":"F","Offense":91,"Defense":67,"Speed":84,"Chemistry":71},
    {"Name":"Turo Lindenvik","Number":71,"Position":"F","Offense":90,"Defense":74,"Speed":82,"Chemistry":73},
    {"Name":"Eriki Bradforovik","Number":22,"Position":"F","Offense":87,"Defense":73,"Speed":81,"Chemistry":76},
    {"Name":"Maximiliana Fabar","Number":63,"Position":"D","Offense":78,"Defense":64,"Speed":77,"Chemistry":67},
    {"Name":"Michaelo Clarkov","Number":18,"Position":"F","Offense":70,"Defense":63,"Speed":74,"Chemistry":67},
    {"Name":"Maxe Balinov","Number":58,"Position":"D","Offense":73,"Defense":77,"Speed":71,"Chemistry":73},
    {"Name":"Lennya Boosin","Number":37,"Position":"F","Offense":68,"Defense":75,"Speed":71,"Chemistry":74},
    {"Name":"Kevine Magintli","Number":6,"Position":"D","Offense":65,"Defense":70,"Speed":71,"Chemistry":72},
    {"Name":"Leona Niederen","Number":17,"Position":"F","Offense":70,"Defense":67,"Speed":69,"Chemistry":66},
    {"Name":"Kevine Orendorsen","Number":78,"Position":"F","Offense":69,"Defense":74,"Speed":69,"Chemistry":72},
    {"Name":"Simona Thien","Number":96,"Position":"F","Offense":67,"Defense":72,"Speed":70,"Chemistry":74},
    {"Name":"Lucase Lessiin","Number":9,"Position":"F","Offense":71,"Defense":54,"Speed":68,"Chemistry":59},
    {"Name":"Luce Tostar","Number":11,"Position":"F","Offense":70,"Defense":75,"Speed":67,"Chemistry":65},
    {"Name":"Eriki Browntto","Number":16,"Position":"F","Offense":67,"Defense":55,"Speed":66,"Chemistry":58},
    {"Name":"Emilo Quaasov","Number":21,"Position":"D","Offense":63,"Defense":72,"Speed":67,"Chemistry":73},
    {"Name":"Kevine Norénnik","Number":14,"Position":"F","Offense":64,"Defense":67,"Speed":66,"Chemistry":70},
    {"Name":"Moritzi Kukukin","Number":26,"Position":"D","Offense":61,"Defense":72,"Speed":67,"Chemistry":73},
    {"Name":"Kristianu Blumenschro","Number":8,"Position":"D","Offense":65,"Defense":70,"Speed":61,"Chemistry":64},
    {"Name":"Nicolasa Geitnar","Number":5,"Position":"D","Offense":60,"Defense":67,"Speed":65,"Chemistry":69},
    {"Name":"Sinani Akdaglek","Number":None,"Position":"D","Offense":59,"Defense":63,"Speed":54,"Chemistry":57},
    {"Name":"Reede Starkar","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":55,"Chemistry":64},
    {"Name":"Daniele Assavolyov","Number":51,"Position":"F","Offense":59,"Defense":74,"Speed":61,"Chemistry":70},
    {"Name":"Joele Hofik","Number":32,"Position":"F","Offense":59,"Defense":73,"Speed":63,"Chemistry":72},
    {"Name":"Davida Rundqvan","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Ryani Olvik","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Nikla Lunear","Number":27,"Position":"G","Offense":74,"Defense":86,"Speed":83,"Chemistry":69},
    {"Name":"Ryani Bednarov","Number":50,"Position":"G","Offense":69,"Defense":84,"Speed":81,"Chemistry":66},
    {"Name":"Leona Hümar","Number":35,"Position":"G","Offense":42,"Defense":81,"Speed":67,"Chemistry":42},
    {"Name":"Seano Kuklokro","Number":77,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40}
  ]
},
{
  "Team": "Frankfurt Core",
  "Momentum": 0,
  "Players": [
    {"Name":"Sebu Cimmermven","Number":61,"Position":"F","Offense":59,"Defense":75,"Speed":53,"Chemistry":62},
    {"Name":"Kevine Bickar","Number":83,"Position":"F","Offense":63,"Defense":73,"Speed":64,"Chemistry":70},
    {"Name":"Fabio Kosvik","Number":20,"Position":"D","Offense":63,"Defense":71,"Speed":69,"Chemistry":74},
    {"Name":"Time Kosvik","Number":22,"Position":"F","Offense":66,"Defense":65,"Speed":65,"Chemistry":65},
    {"Name":"Linusa Frötli","Number":71,"Position":"F","Offense":77,"Defense":62,"Speed":79,"Chemistry":68},
    {"Name":"Camerone Bracar","Number":86,"Position":"F","Offense":83,"Defense":70,"Speed":77,"Chemistry":73},
    {"Name":"Makso Matushkov","Number":52,"Position":"D","Offense":77,"Defense":58,"Speed":76,"Chemistry":63},
    {"Name":"Tyi Glovtto","Number":7,"Position":"F","Offense":72,"Defense":61,"Speed":75,"Chemistry":67},
    {"Name":"Christophera Wilkiinov","Number":84,"Position":"F","Offense":75,"Defense":42,"Speed":72,"Chemistry":56},
    {"Name":"Michaelo Joyauxtto","Number":49,"Position":"D","Offense":69,"Defense":58,"Speed":73,"Chemistry":67},
    {"Name":"Daniele Pfaffengen","Number":77,"Position":"F","Offense":70,"Defense":62,"Speed":73,"Chemistry":67},
    {"Name":"Mati Wedmanovik","Number":67,"Position":"F","Offense":69,"Defense":44,"Speed":72,"Chemistry":59},
    {"Name":"Dennise Lobachro","Number":26,"Position":"F","Offense":73,"Defense":48,"Speed":71,"Chemistry":61},
    {"Name":"Jakobu Liljlek","Number":10,"Position":"F","Offense":69,"Defense":66,"Speed":69,"Chemistry":63},
    {"Name":"Ryani McKierntto","Number":58,"Position":"D","Offense":66,"Defense":54,"Speed":71,"Chemistry":65},
    {"Name":"Cartere Rowneyovik","Number":17,"Position":"F","Offense":64,"Defense":73,"Speed":69,"Chemistry":73},
    {"Name":"Noahi Dunhamro","Number":12,"Position":"F","Offense":63,"Defense":68,"Speed":69,"Chemistry":72},
    {"Name":"Nathi Burnsvik","Number":8,"Position":"F","Offense":64,"Defense":70,"Speed":63,"Chemistry":65},
    {"Name":"Tommye Pasanen","Number":16,"Position":"D","Offense":61,"Defense":62,"Speed":66,"Chemistry":66},
    {"Name":"Markusu Schweigdunov","Number":64,"Position":"F","Offense":62,"Defense":62,"Speed":68,"Chemistry":66},
    {"Name":"Cartere Proftin","Number":15,"Position":"F","Offense":62,"Defense":67,"Speed":61,"Chemistry":63},
    {"Name":"Reida McNeilov","Number":4,"Position":"D","Offense":61,"Defense":54,"Speed":64,"Chemistry":60},
    {"Name":"Daniele Wirtvik","Number":76,"Position":"D","Offense":61,"Defense":64,"Speed":62,"Chemistry":65},
    {"Name":"Codye Brennov","Number":51,"Position":"G","Offense":72,"Defense":84,"Speed":84,"Chemistry":65},
    {"Name":"Mirke Pantkowsov","Number":30,"Position":"G","Offense":84,"Defense":85,"Speed":89,"Chemistry":78},
    {"Name":"Rodione Schumachdunov","Number":74,"Position":"G","Offense":41,"Defense":70,"Speed":60,"Chemistry":41}
  ]
},
{
  "Team": "Iserlohn Miners",
  "Momentum": 0,
  "Players": [
    {"Name":"Lui Niehustto","Number":26,"Position":"D","Offense":59,"Defense":62,"Speed":64,"Chemistry":67},
    {"Name":"Daniele Fischbsen","Number":71,"Position":"F","Offense":88,"Defense":61,"Speed":81,"Chemistry":68},
    {"Name":"Colino Ugbekilov","Number":79,"Position":"D","Offense":75,"Defense":71,"Speed":80,"Chemistry":75},
    {"Name":"Ericu Cornvik","Number":18,"Position":"F","Offense":78,"Defense":67,"Speed":79,"Chemistry":70},
    {"Name":"Juliano Napravndunov","Number":75,"Position":"F","Offense":80,"Defense":68,"Speed":77,"Chemistry":71},
    {"Name":"Christiana Thomastto","Number":27,"Position":"F","Offense":80,"Defense":62,"Speed":77,"Chemistry":66},
    {"Name":"Kyli Woodik","Number":3,"Position":"D","Offense":69,"Defense":70,"Speed":72,"Chemistry":72},
    {"Name":"Tylera Bolandlek","Number":10,"Position":"F","Offense":70,"Defense":69,"Speed":71,"Chemistry":72},
    {"Name":"Eiriki Salsten","Number":17,"Position":"F","Offense":69,"Defense":63,"Speed":71,"Chemistry":67},
    {"Name":"Taro Jentzscven","Number":90,"Position":"F","Offense":66,"Defense":70,"Speed":67,"Chemistry":69},
    {"Name":"Johe Husstli","Number":55,"Position":"D","Offense":63,"Defense":62,"Speed":69,"Chemistry":67},
    {"Name":"Henrike Törnqvven","Number":11,"Position":"F","Offense":68,"Defense":70,"Speed":68,"Chemistry":72},
    {"Name":"Anthonyu Camarven","Number":36,"Position":"F","Offense":67,"Defense":69,"Speed":66,"Chemistry":62},
    {"Name":"Matiasu Lasen","Number":15,"Position":"D","Offense":63,"Defense":68,"Speed":66,"Chemistry":68},
    {"Name":"Coltona Jobksen","Number":77,"Position":"D","Offense":62,"Defense":70,"Speed":62,"Chemistry":66},
    {"Name":"Robino Norelltto","Number":56,"Position":"D","Offense":60,"Defense":49,"Speed":68,"Chemistry":62},
    {"Name":"Macoyi Erkampin","Number":20,"Position":"D","Offense":59,"Defense":62,"Speed":66,"Chemistry":68},
    {"Name":"Bencu Farkastto","Number":40,"Position":"F","Offense":59,"Defense":74,"Speed":55,"Chemistry":64},
    {"Name":"Goro Radionik","Number":7,"Position":"D","Offense":59,"Defense":70,"Speed":55,"Chemistry":64},
    {"Name":"Mano Alinov","Number":63,"Position":"F","Offense":59,"Defense":71,"Speed":58,"Chemistry":66},
    {"Name":"Nilso Eltenovik","Number":4,"Position":"D","Offense":59,"Defense":73,"Speed":60,"Chemistry":69},
    {"Name":"Daniele Geigtto","Number":8,"Position":"F","Offense":59,"Defense":69,"Speed":61,"Chemistry":67},
    {"Name":"Noela Saffrro","Number":14,"Position":"F","Offense":59,"Defense":72,"Speed":61,"Chemistry":69},
    {"Name":"Jakuba Borzeckro","Number":29,"Position":"F","Offense":59,"Defense":70,"Speed":63,"Chemistry":69},
    {"Name":"Daniele Neuven","Number":22,"Position":"F","Offense":59,"Defense":68,"Speed":66,"Chemistry":70},
    {"Name":"Hendrike Hantto","Number":32,"Position":"G","Offense":70,"Defense":87,"Speed":82,"Chemistry":62},
    {"Name":"Andi Jenikdunov","Number":92,"Position":"G","Offense":81,"Defense":86,"Speed":86,"Chemistry":74}
  ]
},
{
  "Team": "Köln Blitzhaie",
  "Momentum": 0,
  "Players": [
    {"Name":"Kevine Niedenar","Number":46,"Position":"F","Offense":61,"Defense":69,"Speed":64,"Chemistry":68},
    {"Name":"Luce Münzenik","Number":75,"Position":"D","Offense":59,"Defense":73,"Speed":54,"Chemistry":63},
    {"Name":"Marca Münzenik","Number":65,"Position":"F","Offense":59,"Defense":72,"Speed":59,"Chemistry":66},
    {"Name":"Grege MacLeinov","Number":89,"Position":"F","Offense":98,"Defense":80,"Speed":91,"Chemistry":81},
    {"Name":"Pata Russelnik","Number":63,"Position":"F","Offense":99,"Defense":80,"Speed":91,"Chemistry":82},
    {"Name":"Natu Schnarven","Number":76,"Position":"F","Offense":87,"Defense":63,"Speed":83,"Chemistry":67},
    {"Name":"Valttera Kemiläinlek","Number":13,"Position":"D","Offense":81,"Defense":79,"Speed":80,"Chemistry":79},
    {"Name":"Dominiki Bokksen","Number":78,"Position":"F","Offense":77,"Defense":71,"Speed":77,"Chemistry":73},
    {"Name":"LouisMarca Aubryik","Number":15,"Position":"F","Offense":74,"Defense":63,"Speed":77,"Chemistry":70},
    {"Name":"Oliwo Kasktli","Number":7,"Position":"D","Offense":75,"Defense":65,"Speed":76,"Chemistry":70},
    {"Name":"Tanno Kerven","Number":10,"Position":"F","Offense":70,"Defense":73,"Speed":75,"Chemistry":73},
    {"Name":"Maximiliana Kammerven","Number":9,"Position":"F","Offense":72,"Defense":71,"Speed":74,"Chemistry":74},
    {"Name":"Ryani MacInndunov","Number":77,"Position":"F","Offense":71,"Defense":71,"Speed":72,"Chemistry":74},
    {"Name":"VeliMatta Vittasmäovik","Number":47,"Position":"D","Offense":67,"Defense":83,"Speed":72,"Chemistry":81},
    {"Name":"Parkera Tuomiov","Number":62,"Position":"F","Offense":70,"Defense":69,"Speed":69,"Chemistry":64},
    {"Name":"Fri Storminov","Number":19,"Position":"F","Offense":68,"Defense":67,"Speed":69,"Chemistry":67},
    {"Name":"Juhanu Tyrväinsen","Number":21,"Position":"F","Offense":67,"Defense":66,"Speed":69,"Chemistry":71},
    {"Name":"Bradya Austinov","Number":57,"Position":"D","Offense":65,"Defense":70,"Speed":70,"Chemistry":74},
    {"Name":"Dominiki Uhen","Number":26,"Position":"F","Offense":63,"Defense":75,"Speed":66,"Chemistry":73},
    {"Name":"Moritzi Müllar","Number":91,"Position":"D","Offense":62,"Defense":61,"Speed":67,"Chemistry":67},
    {"Name":"Maximiliana Glötzlsen","Number":22,"Position":"D","Offense":60,"Defense":70,"Speed":66,"Chemistry":73},
    {"Name":"Robino Calstar","Number":5,"Position":"F","Offense":60,"Defense":75,"Speed":61,"Chemistry":70},
    {"Name":"Maxe Ziergiebar","Number":68,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Jano Sennhenik","Number":17,"Position":"D","Offense":59,"Defense":69,"Speed":55,"Chemistry":62},
    {"Name":"Steni Fischven","Number":74,"Position":"D","Offense":59,"Defense":71,"Speed":61,"Chemistry":69},
    {"Name":"Jannu Juvonven","Number":30,"Position":"G","Offense":69,"Defense":90,"Speed":82,"Chemistry":74},
    {"Name":"Felixe Brücklek","Number":90,"Position":"G","Offense":60,"Defense":87,"Speed":77,"Chemistry":60},
    {"Name":"Toba Ancickvik","Number":45,"Position":"G","Offense":60,"Defense":80,"Speed":75,"Chemistry":58},
    {"Name":"Aaronu Kaisdunov","Number":29,"Position":"G","Offense":42,"Defense":64,"Speed":63,"Chemistry":42}
  ]
},
{
  "Team": "Krefeld Kernschlag",
  "Momentum": 0,
  "Players": [
    {"Name":"Marcu Müllar","Number":9,"Position":"F","Offense":94,"Defense":70,"Speed":87,"Chemistry":74},
    {"Name":"Maxe Newtonik","Number":37,"Position":"F","Offense":89,"Defense":64,"Speed":83,"Chemistry":69},
    {"Name":"Davisa Vandanven","Number":55,"Position":"D","Offense":84,"Defense":79,"Speed":82,"Chemistry":77},
    {"Name":"Jonathane Matsumik","Number":11,"Position":"F","Offense":77,"Defense":73,"Speed":81,"Chemistry":75},
    {"Name":"Mathe Santoslek","Number":95,"Position":"F","Offense":89,"Defense":57,"Speed":80,"Chemistry":65},
    {"Name":"Daniele Bruchtto","Number":26,"Position":"F","Offense":78,"Defense":64,"Speed":76,"Chemistry":72},
    {"Name":"Philu Gogullik","Number":87,"Position":"F","Offense":77,"Defense":65,"Speed":76,"Chemistry":68},
    {"Name":"Marki Zengerlov","Number":89,"Position":"F","Offense":72,"Defense":77,"Speed":76,"Chemistry":76},
    {"Name":"Adamo Payerlven","Number":90,"Position":"F","Offense":84,"Defense":66,"Speed":75,"Chemistry":69},
    {"Name":"Ale Weissin","Number":43,"Position":"F","Offense":77,"Defense":77,"Speed":74,"Chemistry":76},
    {"Name":"Zacka Dybowskovik","Number":44,"Position":"D","Offense":67,"Defense":75,"Speed":71,"Chemistry":75},
    {"Name":"Stevene Raabik","Number":41,"Position":"D","Offense":66,"Defense":73,"Speed":71,"Chemistry":73},
    {"Name":"Roopu Mäkitalik","Number":91,"Position":"F","Offense":69,"Defense":69,"Speed":68,"Chemistry":67},
    {"Name":"Tima Schützan","Number":38,"Position":"F","Offense":66,"Defense":71,"Speed":68,"Chemistry":70},
    {"Name":"Maximiliana Hopsen","Number":67,"Position":"F","Offense":63,"Defense":76,"Speed":66,"Chemistry":72},
    {"Name":"Davida Cernyinov","Number":29,"Position":"F","Offense":67,"Defense":68,"Speed":64,"Chemistry":66},
    {"Name":"Carlo Konztli","Number":47,"Position":"D","Offense":63,"Defense":75,"Speed":66,"Chemistry":75},
    {"Name":"Micka Köhltli","Number":77,"Position":"D","Offense":61,"Defense":78,"Speed":67,"Chemistry":77},
    {"Name":"Oliveri Mebusov","Number":22,"Position":"D","Offense":61,"Defense":73,"Speed":62,"Chemistry":69},
    {"Name":"Nicli Focksvik","Number":71,"Position":"F","Offense":61,"Defense":71,"Speed":58,"Chemistry":63},
    {"Name":"Leonharda Koruslek","Number":56,"Position":"D","Offense":59,"Defense":66,"Speed":54,"Chemistry":60},
    {"Name":"Eriki Buschik","Number":15,"Position":"D","Offense":59,"Defense":75,"Speed":59,"Chemistry":70},
    {"Name":"Jano Nijenhven","Number":94,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Felixe Bickar","Number":31,"Position":"G","Offense":88,"Defense":88,"Speed":89,"Chemistry":88},
    {"Name":"Jule Schultov","Number":30,"Position":"G","Offense":51,"Defense":84,"Speed":72,"Chemistry":50},
    {"Name":"Ola Blumenkan","Number":73,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40}
  ]
},
{
  "Team": "Kassel Zenit",
  "Momentum": 0,
  "Players": [
    {"Name":"Tristano Keckvik","Number":71,"Position":"F","Offense":89,"Defense":74,"Speed":81,"Chemistry":73},
    {"Name":"Tylera Benik","Number":17,"Position":"F","Offense":84,"Defense":75,"Speed":81,"Chemistry":73},
    {"Name":"Dominicu Turgetto","Number":91,"Position":"F","Offense":87,"Defense":75,"Speed":79,"Chemistry":75},
    {"Name":"Hunti Garlenar","Number":65,"Position":"F","Offense":82,"Defense":71,"Speed":78,"Chemistry":71},
    {"Name":"Boda Wildven","Number":4,"Position":"D","Offense":71,"Defense":77,"Speed":74,"Chemistry":76},
    {"Name":"Mita Hoelschinov","Number":44,"Position":"F","Offense":70,"Defense":70,"Speed":73,"Chemistry":72},
    {"Name":"Jake Weidnar","Number":11,"Position":"F","Offense":72,"Defense":74,"Speed":72,"Chemistry":74},
    {"Name":"Yanno Valentin","Number":26,"Position":"F","Offense":72,"Defense":68,"Speed":72,"Chemistry":70},
    {"Name":"Andrewe Bodnarchro","Number":10,"Position":"D","Offense":70,"Defense":71,"Speed":71,"Chemistry":71},
    {"Name":"Darra Mieszkowsovik","Number":66,"Position":"F","Offense":68,"Defense":79,"Speed":71,"Chemistry":78},
    {"Name":"Simona Schützan","Number":97,"Position":"D","Offense":67,"Defense":74,"Speed":71,"Chemistry":74},
    {"Name":"Michaelo Bartulin","Number":27,"Position":"F","Offense":74,"Defense":67,"Speed":70,"Chemistry":71},
    {"Name":"Tima Bendar","Number":55,"Position":"D","Offense":67,"Defense":70,"Speed":69,"Chemistry":68},
    {"Name":"Hanse Detschin","Number":89,"Position":"F","Offense":65,"Defense":79,"Speed":69,"Chemistry":75},
    {"Name":"Laurine Braunovik","Number":18,"Position":"F","Offense":67,"Defense":69,"Speed":69,"Chemistry":72},
    {"Name":"Colino Smithar","Number":None,"Position":"F","Offense":66,"Defense":70,"Speed":70,"Chemistry":63},
    {"Name":"Kasparsi Daugaven","Number":16,"Position":"F","Offense":68,"Defense":76,"Speed":72,"Chemistry":65},
    {"Name":"Macieji Rutkowstli","Number":12,"Position":"F","Offense":64,"Defense":74,"Speed":67,"Chemistry":72},
    {"Name":"Benu Stadldunov","Number":28,"Position":"D","Offense":64,"Defense":75,"Speed":64,"Chemistry":70},
    {"Name":"Clemenso Sagven","Number":34,"Position":"F","Offense":61,"Defense":72,"Speed":64,"Chemistry":70},
    {"Name":"Marca Müllar","Number":22,"Position":"D","Offense":61,"Defense":72,"Speed":61,"Chemistry":68},
    {"Name":"Mano Schamsov","Number":6,"Position":"D","Offense":60,"Defense":73,"Speed":60,"Chemistry":68},
    {"Name":"Christiana Schilinar","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Phe Maurar","Number":33,"Position":"G","Offense":83,"Defense":89,"Speed":88,"Chemistry":85},
    {"Name":"Olego Shilinik","Number":90,"Position":"G","Offense":52,"Defense":85,"Speed":72,"Chemistry":53},
    {"Name":"Bru Maxwelen","Number":31,"Position":"G","Offense":43,"Defense":79,"Speed":66,"Chemistry":43},
    {"Name":"Nicke Neufelov","Number":29,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40}
  ]
},
{
  "Team": "Wolfsburg Voltsturm",
  "Momentum": 0,
  "Players": [
    {"Name":"Mati Whitinov","Number":97,"Position":"F","Offense":87,"Defense":65,"Speed":81,"Chemistry":69},
    {"Name":"Tylera Gaudetvik","Number":58,"Position":"F","Offense":80,"Defense":66,"Speed":80,"Chemistry":70},
    {"Name":"Ethano Prowovik","Number":6,"Position":"D","Offense":74,"Defense":68,"Speed":80,"Chemistry":72},
    {"Name":"Spo Machacven","Number":93,"Position":"F","Offense":85,"Defense":68,"Speed":79,"Chemistry":73},
    {"Name":"Jimmya Lambersen","Number":7,"Position":"F","Offense":84,"Defense":73,"Speed":79,"Chemistry":74},
    {"Name":"Justinu Fesik","Number":71,"Position":"F","Offense":79,"Defense":77,"Speed":75,"Chemistry":77},
    {"Name":"Juliano Chrobven","Number":40,"Position":"F","Offense":76,"Defense":75,"Speed":76,"Chemistry":79},
    {"Name":"Fabio Pfohlro","Number":95,"Position":"D","Offense":71,"Defense":72,"Speed":76,"Chemistry":74},
    {"Name":"Robu Lynchen","Number":49,"Position":"F","Offense":77,"Defense":62,"Speed":75,"Chemistry":66},
    {"Name":"Jacobe Hayhursan","Number":15,"Position":"F","Offense":74,"Defense":66,"Speed":74,"Chemistry":68},
    {"Name":"Matto Choupanin","Number":89,"Position":"F","Offense":77,"Defense":68,"Speed":73,"Chemistry":67},
    {"Name":"Keate Thompov","Number":4,"Position":"D","Offense":70,"Defense":73,"Speed":74,"Chemistry":75},
    {"Name":"Juliano Melchiovik","Number":44,"Position":"D","Offense":69,"Defense":72,"Speed":73,"Chemistry":74},
    {"Name":"Luisa Schinktli","Number":63,"Position":"F","Offense":68,"Defense":62,"Speed":70,"Chemistry":65},
    {"Name":"Jimmya Martinovlek","Number":28,"Position":"D","Offense":62,"Defense":71,"Speed":69,"Chemistry":74},
    {"Name":"Time Ruckdäschlek","Number":91,"Position":"F","Offense":64,"Defense":70,"Speed":68,"Chemistry":74},
    {"Name":"Svenu Zieglven","Number":52,"Position":"F","Offense":62,"Defense":65,"Speed":63,"Chemistry":64},
    {"Name":"Janika Mösvik","Number":24,"Position":"D","Offense":62,"Defense":71,"Speed":66,"Chemistry":72},
    {"Name":"Björnu Kruppen","Number":5,"Position":"D","Offense":60,"Defense":69,"Speed":60,"Chemistry":66},
    {"Name":"Tilu Raabov","Number":74,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":62},
    {"Name":"Jule Ramosinov","Number":50,"Position":"F","Offense":59,"Defense":70,"Speed":63,"Chemistry":70},
    {"Name":"Lucase Dumontsen","Number":13,"Position":"F","Offense":59,"Defense":72,"Speed":66,"Chemistry":73},
    {"Name":"Lea Hafenrichtik","Number":29,"Position":"D","Offense":59,"Defense":70,"Speed":66,"Chemistry":73},
    {"Name":"Dustino Strahlmeiar","Number":1,"Position":"G","Offense":84,"Defense":88,"Speed":88,"Chemistry":83},
    {"Name":"Hannibalu Weitzdunov","Number":67,"Position":"G","Offense":66,"Defense":85,"Speed":79,"Chemistry":61}
  ]
},
{
  "Team": "Whiteout Berlin",
  "Momentum": 0,
  "Players": [
    {"Name":"Mateju Ledenov","Number":33,"Position":"D","Offense":61,"Defense":72,"Speed":66,"Chemistry":74},
    {"Name":"Norwinu Panochdunov","Number":75,"Position":"D","Offense":60,"Defense":66,"Speed":67,"Chemistry":71},
    {"Name":"Jonasu Müllar","Number":18,"Position":"D","Offense":68,"Defense":66,"Speed":73,"Chemistry":71},
    {"Name":"Ericu Hördlinov","Number":77,"Position":"F","Offense":60,"Defense":69,"Speed":67,"Chemistry":72},
    {"Name":"Fri Tiffelar","Number":95,"Position":"F","Offense":84,"Defense":77,"Speed":86,"Chemistry":78},
    {"Name":"Tyi Ronninsen","Number":9,"Position":"F","Offense":93,"Defense":76,"Speed":83,"Chemistry":75},
    {"Name":"Liamu Kirkven","Number":94,"Position":"F","Offense":89,"Defense":73,"Speed":82,"Chemistry":76},
    {"Name":"Leonharda Pfödersen","Number":93,"Position":"F","Offense":84,"Defense":71,"Speed":81,"Chemistry":75},
    {"Name":"Andi Edtli","Number":43,"Position":"F","Offense":82,"Defense":76,"Speed":80,"Chemistry":78},
    {"Name":"Markusu Vikingstovik","Number":37,"Position":"F","Offense":85,"Defense":81,"Speed":79,"Chemistry":82},
    {"Name":"Ericu Mikik","Number":12,"Position":"D","Offense":72,"Defense":83,"Speed":75,"Chemistry":81},
    {"Name":"Mita Reinknik","Number":5,"Position":"D","Offense":72,"Defense":74,"Speed":73,"Chemistry":75},
    {"Name":"Leane Bergen","Number":10,"Position":"F","Offense":68,"Defense":67,"Speed":73,"Chemistry":72},
    {"Name":"Yannicku Veillenik","Number":38,"Position":"F","Offense":71,"Defense":56,"Speed":72,"Chemistry":65},
    {"Name":"Blainu Byronvik","Number":23,"Position":"F","Offense":70,"Defense":73,"Speed":69,"Chemistry":69},
    {"Name":"Marcu Noebellek","Number":92,"Position":"F","Offense":70,"Defense":76,"Speed":69,"Chemistry":71},
    {"Name":"Mano Wiederik","Number":21,"Position":"F","Offense":67,"Defense":73,"Speed":71,"Chemistry":76},
    {"Name":"Korbiniani Geibov","Number":40,"Position":"D","Offense":66,"Defense":72,"Speed":63,"Chemistry":67},
    {"Name":"Pata Khodorenovik","Number":13,"Position":"F","Offense":67,"Defense":69,"Speed":68,"Chemistry":61},
    {"Name":"Lestera Lancastinov","Number":74,"Position":"D","Offense":63,"Defense":72,"Speed":63,"Chemistry":67},
    {"Name":"Adamo Smithar","Number":4,"Position":"D","Offense":61,"Defense":73,"Speed":68,"Chemistry":75},
    {"Name":"Jeu Denik","Number":17,"Position":"F","Offense":63,"Defense":67,"Speed":59,"Chemistry":60},
    {"Name":"Markusu Niemeläinan","Number":56,"Position":"D","Offense":59,"Defense":72,"Speed":53,"Chemistry":62},
    {"Name":"Jake Hildebrro","Number":30,"Position":"G","Offense":94,"Defense":89,"Speed":93,"Chemistry":90},
    {"Name":"Jonasu Stettmov","Number":1,"Position":"G","Offense":58,"Defense":83,"Speed":75,"Chemistry":54}
  ]
}
]

sued_teams = [
{
  "Team": "Augsburg Ferox",
  "Momentum": 0,
  "Players": [
    {"Name":"Ale Greniov","Number":82,"Position":"F","Offense":87,"Defense":74,"Speed":83,"Chemistry":76},
    {"Name":"Dono Busdekvik","Number":14,"Position":"F","Offense":92,"Defense":70,"Speed":83,"Chemistry":74},
    {"Name":"Ale Blankov","Number":26,"Position":"F","Offense":85,"Defense":76,"Speed":83,"Chemistry":79},
    {"Name":"Rileyu Damiansen","Number":19,"Position":"F","Offense":88,"Defense":66,"Speed":80,"Chemistry":70},
    {"Name":"Codye Kunyken","Number":20,"Position":"F","Offense":78,"Defense":65,"Speed":79,"Chemistry":70},
    {"Name":"Tima Wohlgemtto","Number":33,"Position":"F","Offense":81,"Defense":75,"Speed":78,"Chemistry":78},
    {"Name":"Kyli Mayhewtli","Number":27,"Position":"D","Offense":74,"Defense":71,"Speed":78,"Chemistry":75},
    {"Name":"Thoma Schemitsik","Number":62,"Position":"D","Offense":72,"Defense":66,"Speed":77,"Chemistry":72},
    {"Name":"Anthonyu Louisovik","Number":18,"Position":"F","Offense":81,"Defense":73,"Speed":75,"Chemistry":73},
    {"Name":"Madisoni Boweydunov","Number":22,"Position":"D","Offense":71,"Defense":70,"Speed":75,"Chemistry":74},
    {"Name":"Josephu Cramarosan","Number":92,"Position":"F","Offense":71,"Defense":69,"Speed":71,"Chemistry":68},
    {"Name":"Ryani Buttonan","Number":55,"Position":"D","Offense":65,"Defense":62,"Speed":73,"Chemistry":69},
    {"Name":"Enra Moralin","Number":52,"Position":"F","Offense":64,"Defense":69,"Speed":70,"Chemistry":71},
    {"Name":"Moritzi Eliasov","Number":46,"Position":"F","Offense":64,"Defense":68,"Speed":68,"Chemistry":69},
    {"Name":"Floriani Eliasov","Number":67,"Position":"F","Offense":64,"Defense":67,"Speed":69,"Chemistry":70},
    {"Name":"Christiana Hankov","Number":25,"Position":"F","Offense":63,"Defense":67,"Speed":69,"Chemistry":70},
    {"Name":"Maximiliana Rennov","Number":58,"Position":"D","Offense":61,"Defense":61,"Speed":69,"Chemistry":69},
    {"Name":"Leona Lindlek","Number":43,"Position":"D","Offense":61,"Defense":64,"Speed":67,"Chemistry":70},
    {"Name":"Thoma Trevelyov","Number":24,"Position":"F","Offense":60,"Defense":73,"Speed":59,"Chemistry":65},
    {"Name":"Lirono Pellizzvik","Number":60,"Position":"D","Offense":59,"Defense":73,"Speed":54,"Chemistry":64},
    {"Name":"Moritzi Wirthnik","Number":9,"Position":"D","Offense":59,"Defense":67,"Speed":58,"Chemistry":64},
    {"Name":"Fabi Pilen","Number":68,"Position":"D","Offense":59,"Defense":72,"Speed":59,"Chemistry":68},
    {"Name":"Michaelo Garteov","Number":34,"Position":"G","Offense":86,"Defense":86,"Speed":90,"Chemistry":77},
    {"Name":"Peytone Jonessen","Number":41,"Position":"G","Offense":72,"Defense":83,"Speed":82,"Chemistry":65}
  ]
},
{
  "Team": "Landshut Lichtkern",
  "Momentum": 0,
  "Players": [
    {"Name":"Tore Immvik","Number":62,"Position":"F","Offense":95,"Defense":67,"Speed":87,"Chemistry":71},
    {"Name":"Trevu Goochan","Number":72,"Position":"F","Offense":91,"Defense":79,"Speed":83,"Chemistry":78},
    {"Name":"Toba Lindvik","Number":9,"Position":"F","Offense":88,"Defense":74,"Speed":82,"Chemistry":74},
    {"Name":"Davida Stiellek","Number":21,"Position":"F","Offense":82,"Defense":72,"Speed":78,"Chemistry":72},
    {"Name":"Davida Elsninov","Number":61,"Position":"F","Offense":76,"Defense":78,"Speed":77,"Chemistry":78},
    {"Name":"Wadi Bergmtto","Number":48,"Position":"D","Offense":73,"Defense":71,"Speed":77,"Chemistry":72},
    {"Name":"Stanislave Dietzlek","Number":67,"Position":"D","Offense":74,"Defense":80,"Speed":75,"Chemistry":77},
    {"Name":"Jesso Koskenkornik","Number":51,"Position":"F","Offense":80,"Defense":83,"Speed":74,"Chemistry":80},
    {"Name":"Yannicku Wenzsen","Number":20,"Position":"F","Offense":75,"Defense":70,"Speed":74,"Chemistry":70},
    {"Name":"Toba Schwardunov","Number":95,"Position":"F","Offense":75,"Defense":69,"Speed":73,"Chemistry":70},
    {"Name":"Martine Hasovik","Number":77,"Position":"D","Offense":66,"Defense":71,"Speed":71,"Chemistry":71},
    {"Name":"Simona Seidlar","Number":17,"Position":"F","Offense":67,"Defense":73,"Speed":69,"Chemistry":72},
    {"Name":"Dylane Plouffven","Number":6,"Position":"D","Offense":67,"Defense":70,"Speed":68,"Chemistry":69},
    {"Name":"Jakobu Mayenschtto","Number":41,"Position":"F","Offense":65,"Defense":65,"Speed":67,"Chemistry":68},
    {"Name":"Ale Derschven","Number":27,"Position":"D","Offense":68,"Defense":73,"Speed":65,"Chemistry":66},
    {"Name":"Juliano Kornelllek","Number":10,"Position":"F","Offense":64,"Defense":73,"Speed":66,"Chemistry":71},
    {"Name":"Eliase Lindnov","Number":44,"Position":"D","Offense":65,"Defense":65,"Speed":64,"Chemistry":63},
    {"Name":"Sei Parkdunov","Number":96,"Position":"F","Offense":64,"Defense":68,"Speed":66,"Chemistry":71},
    {"Name":"Andi Schwardunov","Number":25,"Position":"D","Offense":65,"Defense":76,"Speed":63,"Chemistry":69},
    {"Name":"Oliveri Stümpsen","Number":93,"Position":"F","Offense":63,"Defense":70,"Speed":62,"Chemistry":67},
    {"Name":"Finni Seriktto","Number":8,"Position":"D","Offense":62,"Defense":63,"Speed":66,"Chemistry":67},
    {"Name":"Pasco Stecknik","Number":43,"Position":"F","Offense":61,"Defense":75,"Speed":58,"Chemistry":64},
    {"Name":"Luisa Scheibengrablek","Number":18,"Position":"F","Offense":61,"Defense":61,"Speed":58,"Chemistry":59},
    {"Name":"Lukasu Gaustto","Number":23,"Position":"F","Offense":59,"Defense":75,"Speed":53,"Chemistry":62},
    {"Name":"Marcu Taberten","Number":71,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Maximiliana Oswalddunov","Number":22,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Jonasu Langlek","Number":34,"Position":"G","Offense":71,"Defense":87,"Speed":82,"Chemistry":66},
    {"Name":"Phe Dietldunov","Number":29,"Position":"G","Offense":71,"Defense":87,"Speed":83,"Chemistry":68},
    {"Name":"Johe Kurrdunov","Number":40,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40},
    {"Name":"Daniele Henten","Number":30,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40}
  ]
},
{
  "Team": "München FluxBullen",
  "Momentum": 0,
  "Players": [
    {"Name":"Phe Krenindunov","Number":79,"Position":"F","Offense":65,"Defense":72,"Speed":68,"Chemistry":73},
    {"Name":"Ria Kaisdunov","Number":18,"Position":"D","Offense":60,"Defense":73,"Speed":60,"Chemistry":68},
    {"Name":"Phe Sinnov","Number":43,"Position":"D","Offense":60,"Defense":72,"Speed":64,"Chemistry":71},
    {"Name":"Taro Hirosdunov","Number":17,"Position":"F","Offense":85,"Defense":83,"Speed":86,"Chemistry":82},
    {"Name":"Adamo Brooksovik","Number":77,"Position":"F","Offense":82,"Defense":73,"Speed":81,"Chemistry":76},
    {"Name":"Yasino Ehlizov","Number":42,"Position":"F","Offense":78,"Defense":75,"Speed":79,"Chemistry":77},
    {"Name":"Toba Riedinov","Number":8,"Position":"F","Offense":84,"Defense":75,"Speed":77,"Chemistry":73},
    {"Name":"Pata Hagik","Number":52,"Position":"F","Offense":79,"Defense":75,"Speed":76,"Chemistry":78},
    {"Name":"Christophera DeSousovik","Number":82,"Position":"F","Offense":80,"Defense":57,"Speed":78,"Chemistry":63},
    {"Name":"Villa Pokkvik","Number":22,"Position":"D","Offense":73,"Defense":76,"Speed":76,"Chemistry":77},
    {"Name":"Markusu Eisenschmlek","Number":11,"Position":"F","Offense":77,"Defense":76,"Speed":75,"Chemistry":76},
    {"Name":"Jeri McKennven","Number":91,"Position":"F","Offense":77,"Defense":70,"Speed":75,"Chemistry":74},
    {"Name":"Gabo Fontaintto","Number":97,"Position":"F","Offense":75,"Defense":70,"Speed":75,"Chemistry":71},
    {"Name":"Ryani Murphyro","Number":24,"Position":"D","Offense":72,"Defense":76,"Speed":75,"Chemistry":74},
    {"Name":"Veita Oswalddunov","Number":27,"Position":"F","Offense":76,"Defense":72,"Speed":74,"Chemistry":75},
    {"Name":"Bradya Ferguinov","Number":12,"Position":"F","Offense":73,"Defense":61,"Speed":73,"Chemistry":68},
    {"Name":"Dille Heatheringttto","Number":95,"Position":"D","Offense":67,"Defense":79,"Speed":71,"Chemistry":78},
    {"Name":"Maximiliana Kastnlek","Number":93,"Position":"F","Offense":66,"Defense":58,"Speed":70,"Chemistry":67},
    {"Name":"Konradu Abeltshausdunov","Number":16,"Position":"D","Offense":63,"Defense":74,"Speed":69,"Chemistry":76},
    {"Name":"Fabio Wagnov","Number":55,"Position":"D","Offense":62,"Defense":74,"Speed":68,"Chemistry":76},
    {"Name":"Maximiliana Daubndunov","Number":70,"Position":"D","Offense":62,"Defense":65,"Speed":63,"Chemistry":65},
    {"Name":"Anto Bibeaovik","Number":30,"Position":"G","Offense":59,"Defense":85,"Speed":76,"Chemistry":57},
    {"Name":"Mathiaso Niederen","Number":35,"Position":"G","Offense":78,"Defense":86,"Speed":84,"Chemistry":80}
  ]
},
{
  "Team": "Mannheim Ventus",
  "Momentum": 0,
  "Players": [
    {"Name":"Nicolasa Mattinlek","Number":52,"Position":"D","Offense":85,"Defense":87,"Speed":82,"Chemistry":83},
    {"Name":"Matthiasu Plachtven","Number":22,"Position":"F","Offense":82,"Defense":77,"Speed":81,"Chemistry":79},
    {"Name":"Marcu Michaelsen","Number":65,"Position":"F","Offense":77,"Defense":74,"Speed":81,"Chemistry":77},
    {"Name":"Anthonyu Grecan","Number":44,"Position":"F","Offense":83,"Defense":73,"Speed":80,"Chemistry":77},
    {"Name":"Kristianu Reichlek","Number":11,"Position":"F","Offense":82,"Defense":76,"Speed":77,"Chemistry":79},
    {"Name":"Justinu Schützan","Number":74,"Position":"F","Offense":79,"Defense":74,"Speed":76,"Chemistry":74},
    {"Name":"Johne Gilmoik","Number":7,"Position":"D","Offense":70,"Defense":72,"Speed":76,"Chemistry":75},
    {"Name":"Zaco Solowlek","Number":73,"Position":"F","Offense":77,"Defense":74,"Speed":75,"Chemistry":76},
    {"Name":"Leona Gawankvik","Number":9,"Position":"D","Offense":72,"Defense":82,"Speed":75,"Chemistry":80},
    {"Name":"Krise Bennettto","Number":21,"Position":"F","Offense":75,"Defense":71,"Speed":73,"Chemistry":76},
    {"Name":"Tome Kühnhacan","Number":34,"Position":"F","Offense":71,"Defense":81,"Speed":73,"Chemistry":75},
    {"Name":"Maximiliana Heimov","Number":86,"Position":"F","Offense":75,"Defense":77,"Speed":73,"Chemistry":79},
    {"Name":"Luko Espositov","Number":19,"Position":"F","Offense":71,"Defense":72,"Speed":71,"Chemistry":72},
    {"Name":"Lukasu Kälbldunov","Number":49,"Position":"D","Offense":69,"Defense":87,"Speed":72,"Chemistry":82},
    {"Name":"Ale Ehlven","Number":28,"Position":"F","Offense":70,"Defense":80,"Speed":70,"Chemistry":78},
    {"Name":"Dani Renoufin","Number":4,"Position":"D","Offense":63,"Defense":85,"Speed":69,"Chemistry":82},
    {"Name":"Yannicku Proskov","Number":27,"Position":"F","Offense":66,"Defense":80,"Speed":68,"Chemistry":81},
    {"Name":"Maxe Penkininov","Number":39,"Position":"F","Offense":64,"Defense":75,"Speed":63,"Chemistry":70},
    {"Name":"Ericu Ubtto","Number":16,"Position":"F","Offense":62,"Defense":67,"Speed":63,"Chemistry":66},
    {"Name":"Haydeno Shawin","Number":82,"Position":"D","Offense":61,"Defense":76,"Speed":63,"Chemistry":73},
    {"Name":"Toba Fohrlven","Number":5,"Position":"D","Offense":59,"Defense":67,"Speed":66,"Chemistry":71},
    {"Name":"Johano Mattsik","Number":33,"Position":"G","Offense":68,"Defense":89,"Speed":81,"Chemistry":70},
    {"Name":"Maximiliana Franzrnik","Number":56,"Position":"G","Offense":83,"Defense":90,"Speed":88,"Chemistry":83}
  ]
},
{
  "Team": "Novadelta Panther",
  "Momentum": 0,
  "Players": [
    {"Name":"Luka Hauven","Number":85,"Position":"F","Offense":59,"Defense":72,"Speed":63,"Chemistry":70},
    {"Name":"Edwin Tropov","Number":55,"Position":"D","Offense":69,"Defense":69,"Speed":69,"Chemistry":72},
    {"Name":"Rilan Barvik","Number":37,"Position":"F","Offense":99,"Defense":81,"Speed":91,"Chemistry":83},
    {"Name":"Mils Powlek","Number":9,"Position":"F","Offense":98,"Defense":78,"Speed":89,"Chemistry":82},
    {"Name":"Ken Agostinov","Number":11,"Position":"F","Offense":96,"Defense":83,"Speed":86,"Chemistry":83},
    {"Name":"Aleks Bratan","Number":75,"Position":"D","Offense":85,"Defense":90,"Speed":84,"Chemistry":85},
    {"Name":"Dano Schmolik","Number":92,"Position":"F","Offense":90,"Defense":80,"Speed":83,"Chemistry":80},
    {"Name":"Abbo Girdunov","Number":17,"Position":"F","Offense":82,"Defense":78,"Speed":79,"Chemistry":77},
    {"Name":"Rileyu Sheentli","Number":91,"Position":"F","Offense":79,"Defense":71,"Speed":79,"Chemistry":74},
    {"Name":"Peteru Abbandoninov","Number":98,"Position":"F","Offense":78,"Defense":79,"Speed":76,"Chemistry":79},
    {"Name":"Aust Keaten","Number":89,"Position":"F","Offense":77,"Defense":80,"Speed":76,"Chemistry":81},
    {"Name":"Leo Hütten","Number":25,"Position":"D","Offense":72,"Defense":90,"Speed":76,"Chemistry":85},
    {"Name":"Dan Pietto","Number":86,"Position":"F","Offense":74,"Defense":81,"Speed":75,"Chemistry":82},
    {"Name":"Morgon Elvik","Number":4,"Position":"D","Offense":71,"Defense":88,"Speed":74,"Chemistry":83},
    {"Name":"Filip Krausen","Number":8,"Position":"F","Offense":73,"Defense":56,"Speed":73,"Chemistry":65},
    {"Name":"Sam Ruvek","Number":2,"Position":"D","Offense":67,"Defense":85,"Speed":72,"Chemistry":81},
    {"Name":"Johan Krausen","Number":16,"Position":"F","Offense":63,"Defense":71,"Speed":69,"Chemistry":73},
    {"Name":"Philu Proti","Number":95,"Position":"D","Offense":63,"Defense":76,"Speed":66,"Chemistry":72},
    {"Name":"Kris Jandro","Number":7,"Position":"D","Offense":62,"Defense":55,"Speed":64,"Chemistry":59},
    {"Name":"Jakina Smallwnik","Number":23,"Position":"F","Offense":63,"Defense":68,"Speed":62,"Chemistry":64},
    {"Name":"Petr Spornik","Number":50,"Position":"D","Offense":60,"Defense":69,"Speed":60,"Chemistry":65},
    {"Name":"Dominiki Zerhocin","Number":13,"Position":"D","Offense":59,"Defense":73,"Speed":52,"Chemistry":61},
    {"Name":"Lukasu Simone Jungovik","Number":5,"Position":"D","Offense":59,"Defense":73,"Speed":52,"Chemistry":61},
    {"Name":"Sam Kharbintli","Number":83,"Position":"F","Offense":59,"Defense":63,"Speed":57,"Chemistry":62},
    {"Name":"Devon Willark","Number":31,"Position":"G","Offense":77,"Defense":86,"Speed":84,"Chemistry":75},
    {"Name":"Bret Brokan","Number":36,"Position":"G","Offense":70,"Defense":86,"Speed":80,"Chemistry":71}
  ]
},
{
  "Team": "Nürnberg Eistiger",
  "Momentum": 0,
  "Players": [
    {"Name":"Jakobu Webik","Number":41,"Position":"D","Offense":66,"Defense":85,"Speed":72,"Chemistry":83},
    {"Name":"Evane Barrattto","Number":10,"Position":"F","Offense":89,"Defense":68,"Speed":90,"Chemistry":73},
    {"Name":"Tylera Spezitto","Number":37,"Position":"F","Offense":91,"Defense":72,"Speed":80,"Chemistry":75},
    {"Name":"Grege Meirelvik","Number":43,"Position":"F","Offense":76,"Defense":70,"Speed":80,"Chemistry":73},
    {"Name":"Samueli DoveMcFalan","Number":75,"Position":"F","Offense":85,"Defense":63,"Speed":79,"Chemistry":72},
    {"Name":"Owene Headricik","Number":47,"Position":"D","Offense":78,"Defense":68,"Speed":78,"Chemistry":72},
    {"Name":"Bretta Murraytto","Number":81,"Position":"F","Offense":86,"Defense":72,"Speed":79,"Chemistry":68},
    {"Name":"Thoma Heiglik","Number":49,"Position":"F","Offense":80,"Defense":80,"Speed":77,"Chemistry":81},
    {"Name":"Cha Gerardar","Number":95,"Position":"F","Offense":76,"Defense":61,"Speed":77,"Chemistry":68},
    {"Name":"Colu Maiar","Number":14,"Position":"F","Offense":82,"Defense":74,"Speed":78,"Chemistry":70},
    {"Name":"Jule Karrsen","Number":6,"Position":"D","Offense":67,"Defense":72,"Speed":73,"Chemistry":75},
    {"Name":"Codye Haiskanov","Number":74,"Position":"D","Offense":68,"Defense":58,"Speed":72,"Chemistry":67},
    {"Name":"Constantinu Braunovik","Number":90,"Position":"D","Offense":69,"Defense":74,"Speed":69,"Chemistry":72},
    {"Name":"Romane Kechtov","Number":73,"Position":"F","Offense":66,"Defense":68,"Speed":67,"Chemistry":67},
    {"Name":"Marcuse Webik","Number":24,"Position":"D","Offense":65,"Defense":78,"Speed":70,"Chemistry":79},
    {"Name":"Jakobu Ustorfin","Number":48,"Position":"F","Offense":65,"Defense":71,"Speed":66,"Chemistry":67},
    {"Name":"Justu Böttninov","Number":9,"Position":"D","Offense":63,"Defense":71,"Speed":69,"Chemistry":75},
    {"Name":"Williame Grabtto","Number":77,"Position":"F","Offense":67,"Defense":62,"Speed":66,"Chemistry":59},
    {"Name":"Time Bakosan","Number":22,"Position":"F","Offense":63,"Defense":75,"Speed":61,"Chemistry":65},
    {"Name":"Josefa Ehamtli","Number":44,"Position":"F","Offense":62,"Defense":62,"Speed":65,"Chemistry":64},
    {"Name":"Eugeni Alanovik","Number":29,"Position":"F","Offense":61,"Defense":71,"Speed":61,"Chemistry":65},
    {"Name":"Luisa Üffingvik","Number":42,"Position":"F","Offense":60,"Defense":70,"Speed":62,"Chemistry":67},
    {"Name":"Nikla Treutlven","Number":31,"Position":"G","Offense":87,"Defense":87,"Speed":91,"Chemistry":79},
    {"Name":"Evane Fitzpatrin","Number":30,"Position":"G","Offense":66,"Defense":85,"Speed":79,"Chemistry":63}
  ]
},
{
  "Team": "Regensburg Pulse",
  "Momentum": 0,
  "Players": [
    {"Name":"Coreye Trivinov","Number":86,"Position":"F","Offense":79,"Defense":62,"Speed":78,"Chemistry":64},
    {"Name":"Pierri Proti","Number":36,"Position":"F","Offense":84,"Defense":65,"Speed":77,"Chemistry":67},
    {"Name":"Samueli Payeuren","Number":17,"Position":"F","Offense":76,"Defense":69,"Speed":75,"Chemistry":72},
    {"Name":"Kevine Slezakdunov","Number":81,"Position":"F","Offense":74,"Defense":74,"Speed":75,"Chemistry":73},
    {"Name":"Davida Morleylek","Number":93,"Position":"F","Offense":78,"Defense":73,"Speed":76,"Chemistry":68},
    {"Name":"Bryco Kindopro","Number":9,"Position":"F","Offense":73,"Defense":72,"Speed":72,"Chemistry":72},
    {"Name":"Constantinu Ontlinov","Number":19,"Position":"F","Offense":74,"Defense":71,"Speed":70,"Chemistry":67},
    {"Name":"Alexe Berardinelik","Number":7,"Position":"F","Offense":71,"Defense":71,"Speed":70,"Chemistry":69},
    {"Name":"Donáti Pétlek","Number":77,"Position":"F","Offense":70,"Defense":71,"Speed":69,"Chemistry":71},
    {"Name":"Niko Gajovsknik","Number":69,"Position":"D","Offense":66,"Defense":62,"Speed":69,"Chemistry":67},
    {"Name":"Yumu Grimmov","Number":22,"Position":"F","Offense":65,"Defense":60,"Speed":69,"Chemistry":65},
    {"Name":"Seano Gilestto","Number":28,"Position":"D","Offense":63,"Defense":71,"Speed":67,"Chemistry":71},
    {"Name":"Jeri Braccnik","Number":97,"Position":"F","Offense":66,"Defense":71,"Speed":66,"Chemistry":62},
    {"Name":"Pata Demetzar","Number":92,"Position":"D","Offense":62,"Defense":66,"Speed":65,"Chemistry":67},
    {"Name":"Guillauma Naudlek","Number":8,"Position":"D","Offense":61,"Defense":65,"Speed":66,"Chemistry":68},
    {"Name":"Nicke Mählar","Number":29,"Position":"D","Offense":61,"Defense":63,"Speed":64,"Chemistry":65},
    {"Name":"Ale Angaran","Number":21,"Position":"F","Offense":61,"Defense":66,"Speed":66,"Chemistry":68},
    {"Name":"Mara Baudunov","Number":11,"Position":"D","Offense":60,"Defense":77,"Speed":60,"Chemistry":70},
    {"Name":"Maximiliana Merklov","Number":18,"Position":"D","Offense":60,"Defense":69,"Speed":64,"Chemistry":70},
    {"Name":"Pasco Zerresvik","Number":16,"Position":"D","Offense":59,"Defense":65,"Speed":65,"Chemistry":69},
    {"Name":"Mateju Giesltto","Number":14,"Position":"F","Offense":59,"Defense":68,"Speed":54,"Chemistry":60},
    {"Name":"Marksi Jirgensdunov","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":55,"Chemistry":65},
    {"Name":"Lukasu Kriegsen","Number":25,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Juliano Elssen","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Viktore Buchnik","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Pasco Aquinen","Number":None,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":61},
    {"Name":"Jonasu Neffindunov","Number":75,"Position":"G","Offense":87,"Defense":90,"Speed":91,"Chemistry":85},
    {"Name":"Konradu Fiedlsen","Number":34,"Position":"G","Offense":55,"Defense":84,"Speed":75,"Chemistry":51},
    {"Name":"Colu Danielsmeiov","Number":49,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40}
  ]
},
{
  "Team": "Ravensburg Zenit Falken",
  "Momentum": 0,
  "Players": [
    {"Name":"Robbii Czarnvik","Number":77,"Position":"F","Offense":90,"Defense":60,"Speed":83,"Chemistry":69},
    {"Name":"Marki Rasselnik","Number":92,"Position":"F","Offense":92,"Defense":79,"Speed":82,"Chemistry":79},
    {"Name":"Eriki Karlsdunov","Number":19,"Position":"F","Offense":80,"Defense":75,"Speed":80,"Chemistry":74},
    {"Name":"Ale Voyinov","Number":42,"Position":"F","Offense":78,"Defense":50,"Speed":74,"Chemistry":61},
    {"Name":"Simona Sezemsktli","Number":93,"Position":"D","Offense":71,"Defense":74,"Speed":73,"Chemistry":73},
    {"Name":"Nicu Lattvik","Number":14,"Position":"F","Offense":75,"Defense":56,"Speed":72,"Chemistry":63},
    {"Name":"Thoma Reichlek","Number":27,"Position":"F","Offense":66,"Defense":71,"Speed":70,"Chemistry":70},
    {"Name":"Juliano Eichinglek","Number":91,"Position":"D","Offense":66,"Defense":76,"Speed":70,"Chemistry":75},
    {"Name":"Marvino Schmidtto","Number":13,"Position":"F","Offense":66,"Defense":67,"Speed":70,"Chemistry":68},
    {"Name":"Aleca Ahlrotvik","Number":24,"Position":"F","Offense":68,"Defense":63,"Speed":67,"Chemistry":64},
    {"Name":"Louise Lattvik","Number":74,"Position":"F","Offense":65,"Defense":63,"Speed":68,"Chemistry":66},
    {"Name":"Denise Pfaffengen","Number":76,"Position":"D","Offense":64,"Defense":72,"Speed":68,"Chemistry":71},
    {"Name":"Phe Massovik","Number":25,"Position":"D","Offense":64,"Defense":67,"Speed":67,"Chemistry":69},
    {"Name":"Flora Ketteren","Number":16,"Position":"D","Offense":66,"Defense":68,"Speed":65,"Chemistry":64},
    {"Name":"Fabio Sartven","Number":9,"Position":"F","Offense":65,"Defense":69,"Speed":66,"Chemistry":70},
    {"Name":"Niki Kesslinov","Number":33,"Position":"F","Offense":62,"Defense":53,"Speed":64,"Chemistry":61},
    {"Name":"Mateju Mrazekdunov","Number":21,"Position":"F","Offense":62,"Defense":72,"Speed":61,"Chemistry":64},
    {"Name":"Ryani Odudar","Number":79,"Position":"D","Offense":60,"Defense":62,"Speed":66,"Chemistry":67},
    {"Name":"Lukasu Jungovik","Number":41,"Position":"D","Offense":60,"Defense":63,"Speed":62,"Chemistry":64},
    {"Name":"Leona Sivicen","Number":83,"Position":"F","Offense":59,"Defense":75,"Speed":52,"Chemistry":62},
    {"Name":"Jano Wieszinslek","Number":66,"Position":"D","Offense":59,"Defense":65,"Speed":55,"Chemistry":60},
    {"Name":"Nicolasa Schindllek","Number":80,"Position":"F","Offense":59,"Defense":72,"Speed":56,"Chemistry":64},
    {"Name":"Anso Gergik","Number":15,"Position":"F","Offense":59,"Defense":72,"Speed":60,"Chemistry":68},
    {"Name":"Ilye Sharipovik","Number":43,"Position":"G","Offense":84,"Defense":82,"Speed":86,"Chemistry":75},
    {"Name":"Niko Pertanov","Number":1,"Position":"G","Offense":54,"Defense":83,"Speed":72,"Chemistry":54},
    {"Name":"Philu Gründlar","Number":87,"Position":"G","Offense":41,"Defense":93,"Speed":70,"Chemistry":41},
    {"Name":"Nica Wiensdunov","Number":3,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40},
    {"Name":"Raphaelo Roedinov","Number":None,"Position":"G","Offense":40,"Defense":61,"Speed":40,"Chemistry":40}
  ]
},
{
  "Team": "Straubing Forest Tigers",
  "Momentum": 0,
  "Players": [
    {"Name":"Linusa Brandlik","Number":73,"Position":"F","Offense":62,"Defense":68,"Speed":66,"Chemistry":70},
    {"Name":"Marcu Brandtin","Number":92,"Position":"D","Offense":90,"Defense":77,"Speed":84,"Chemistry":76},
    {"Name":"Nicholasu Hallorar","Number":71,"Position":"F","Offense":90,"Defense":81,"Speed":84,"Chemistry":81},
    {"Name":"Elisu Hedov","Number":75,"Position":"F","Offense":88,"Defense":81,"Speed":80,"Chemistry":82},
    {"Name":"Stefane Loibldunov","Number":38,"Position":"F","Offense":78,"Defense":70,"Speed":80,"Chemistry":74},
    {"Name":"Justinu Scottro","Number":20,"Position":"F","Offense":80,"Defense":73,"Speed":76,"Chemistry":76},
    {"Name":"Wadi Alliven","Number":88,"Position":"F","Offense":79,"Defense":75,"Speed":76,"Chemistry":75},
    {"Name":"Danju Leonharik","Number":53,"Position":"F","Offense":72,"Defense":73,"Speed":77,"Chemistry":77},
    {"Name":"Alexe Greenar","Number":6,"Position":"D","Offense":76,"Defense":75,"Speed":76,"Chemistry":76},
    {"Name":"Filipi Varejckov","Number":90,"Position":"F","Offense":77,"Defense":73,"Speed":76,"Chemistry":76},
    {"Name":"Tylera Maddenro","Number":18,"Position":"F","Offense":77,"Defense":75,"Speed":76,"Chemistry":70},
    {"Name":"Tima Fleischtto","Number":91,"Position":"F","Offense":74,"Defense":72,"Speed":75,"Chemistry":75},
    {"Name":"Nicolasa Beaudan","Number":7,"Position":"D","Offense":70,"Defense":79,"Speed":73,"Chemistry":78},
    {"Name":"Joshe Melnicov","Number":37,"Position":"F","Offense":71,"Defense":76,"Speed":73,"Chemistry":78},
    {"Name":"Tima Brunnhubinov","Number":19,"Position":"F","Offense":68,"Defense":73,"Speed":72,"Chemistry":76},
    {"Name":"Zaco Leslinik","Number":8,"Position":"D","Offense":69,"Defense":71,"Speed":70,"Chemistry":69},
    {"Name":"Adriano Kleintli","Number":17,"Position":"D","Offense":68,"Defense":68,"Speed":71,"Chemistry":72},
    {"Name":"Skyle McKenzvik","Number":86,"Position":"F","Offense":68,"Defense":71,"Speed":69,"Chemistry":72},
    {"Name":"Marie Zimmerar","Number":13,"Position":"D","Offense":65,"Defense":75,"Speed":68,"Chemistry":73},
    {"Name":"Stephana Daschnov","Number":9,"Position":"D","Offense":62,"Defense":79,"Speed":69,"Chemistry":79},
    {"Name":"Ryani Merklik","Number":58,"Position":"D","Offense":68,"Defense":64,"Speed":63,"Chemistry":58},
    {"Name":"Michaelo Connollnik","Number":22,"Position":"F","Offense":62,"Defense":72,"Speed":61,"Chemistry":64},
    {"Name":"Henrike Haukelik","Number":40,"Position":"G","Offense":95,"Defense":89,"Speed":92,"Chemistry":99},
    {"Name":"Floriani Buglov","Number":1,"Position":"G","Offense":53,"Defense":80,"Speed":72,"Chemistry":52}
  ]
},
{
  "Team": "Schwenningen Sturmflügel",
  "Momentum": 0,
  "Players": [
    {"Name":"Nicli Hempinov","Number":61,"Position":"D","Offense":59,"Defense":69,"Speed":58,"Chemistry":65},
    {"Name":"Nikla Hübndunov","Number":72,"Position":"D","Offense":61,"Defense":74,"Speed":64,"Chemistry":72},
    {"Name":"Tysono Spinkar","Number":96,"Position":"F","Offense":85,"Defense":71,"Speed":78,"Chemistry":76},
    {"Name":"Tylora Spinkar","Number":90,"Position":"F","Offense":79,"Defense":70,"Speed":77,"Chemistry":75},
    {"Name":"Kyli Platzov","Number":88,"Position":"F","Offense":74,"Defense":65,"Speed":77,"Chemistry":72},
    {"Name":"Ale Karachinov","Number":47,"Position":"F","Offense":79,"Defense":61,"Speed":77,"Chemistry":71},
    {"Name":"Zachi Senyshyro","Number":89,"Position":"F","Offense":83,"Defense":75,"Speed":76,"Chemistry":76},
    {"Name":"Ericu Martinstli","Number":46,"Position":"D","Offense":70,"Defense":79,"Speed":76,"Chemistry":79},
    {"Name":"Daniele OReganovik","Number":11,"Position":"F","Offense":79,"Defense":72,"Speed":75,"Chemistry":69},
    {"Name":"Philu Hungereckdunov","Number":94,"Position":"F","Offense":73,"Defense":76,"Speed":74,"Chemistry":77},
    {"Name":"Jorde Szwarzar","Number":14,"Position":"F","Offense":71,"Defense":70,"Speed":73,"Chemistry":72},
    {"Name":"Sebu Uvirtli","Number":93,"Position":"F","Offense":69,"Defense":64,"Speed":74,"Chemistry":72},
    {"Name":"Thoma Larkinik","Number":37,"Position":"D","Offense":68,"Defense":69,"Speed":74,"Chemistry":74},
    {"Name":"Mirke Höfflro","Number":10,"Position":"F","Offense":69,"Defense":68,"Speed":72,"Chemistry":70},
    {"Name":"Alexe Trivellvik","Number":53,"Position":"D","Offense":67,"Defense":71,"Speed":71,"Chemistry":71},
    {"Name":"Boazo Basov","Number":64,"Position":"F","Offense":69,"Defense":65,"Speed":72,"Chemistry":72},
    {"Name":"Håkone Häneltik","Number":19,"Position":"F","Offense":66,"Defense":71,"Speed":71,"Chemistry":71},
    {"Name":"Benu Marshaltto","Number":54,"Position":"D","Offense":64,"Defense":68,"Speed":71,"Chemistry":72},
    {"Name":"Arko Dziambovik","Number":16,"Position":"D","Offense":68,"Defense":73,"Speed":69,"Chemistry":74},
    {"Name":"Dominiki Bittnlek","Number":7,"Position":"D","Offense":63,"Defense":71,"Speed":67,"Chemistry":72},
    {"Name":"Tima Gettingsen","Number":26,"Position":"F","Offense":65,"Defense":78,"Speed":64,"Chemistry":67},
    {"Name":"Philu Feistov","Number":9,"Position":"F","Offense":64,"Defense":70,"Speed":61,"Chemistry":63},
    {"Name":"Felixe Scheven","Number":13,"Position":"F","Offense":63,"Defense":74,"Speed":62,"Chemistry":68},
    {"Name":"Williame Webik","Number":78,"Position":"D","Offense":62,"Defense":66,"Speed":66,"Chemistry":68},
    {"Name":"Joacimi Erikstli","Number":60,"Position":"G","Offense":92,"Defense":90,"Speed":93,"Chemistry":91},
    {"Name":"Michaelo Bitzven","Number":1,"Position":"G","Offense":64,"Defense":85,"Speed":78,"Chemistry":60}
  ]
}
]
